// This file is generated by "defs2struct.py".
// Please do not edit.

#include "chatbskyconvogetunreadcounts.h"
#include "atprotocol/lexicons_func.h"
#include "atprotocol/lexicons_func_unknown.h"

#include <QJsonDocument>
#include <QJsonObject>
#include <QUrlQuery>

namespace AtProtocolInterface {

ChatBskyConvoGetUnreadCounts::ChatBskyConvoGetUnreadCounts(QObject *parent)
    : AccessAtProtocol { parent }
{
}

void ChatBskyConvoGetUnreadCounts::getUnreadCounts(const bool includeGroupChats)
{
    QUrlQuery url_query;
    if (includeGroupChats) {
        url_query.addQueryItem(QStringLiteral("includeGroupChats"), "true");
    }

    get(QStringLiteral("xrpc/chat.bsky.convo.getUnreadCounts"), url_query);
}

const int &ChatBskyConvoGetUnreadCounts::unreadAcceptedConvos() const
{
    return m_unreadAcceptedConvos;
}

const int &ChatBskyConvoGetUnreadCounts::unreadRequestConvos() const
{
    return m_unreadRequestConvos;
}

bool ChatBskyConvoGetUnreadCounts::parseJson(bool success, const QString reply_json)
{
    QJsonDocument json_doc = QJsonDocument::fromJson(reply_json.toUtf8());
    if (json_doc.isEmpty()) {
        success = false;
    } else {
        AtProtocolType::LexiconsTypeUnknown::copyInt(
                json_doc.object().value("unreadAcceptedConvos"), m_unreadAcceptedConvos);
        AtProtocolType::LexiconsTypeUnknown::copyInt(json_doc.object().value("unreadRequestConvos"),
                                                     m_unreadRequestConvos);
    }

    return success;
}

}
