// This file is generated by "defs2struct.py".
// Please do not edit.

#ifndef APPBSKYGRAPHGETBLOCKS_H
#define APPBSKYGRAPHGETBLOCKS_H

#include "atprotocol/app/bsky/graph/appbskygraphgetfollows.h"

namespace AtProtocolInterface {

class AppBskyGraphGetBlocks : public AppBskyGraphGetFollows
{
public:
    explicit AppBskyGraphGetBlocks(QObject *parent = nullptr);

    void getBlocks(const int limit, const QString &cursor);
};

}

#endif // APPBSKYGRAPHGETBLOCKS_H
