// This file is generated by "defs2struct.py".
// Please do not edit.

#ifndef APPBSKYGRAPHGETFOLLOWERS_H
#define APPBSKYGRAPHGETFOLLOWERS_H

#include "atprotocol/app/bsky/graph/appbskygraphgetfollows.h"

namespace AtProtocolInterface {

class AppBskyGraphGetFollowers : public AppBskyGraphGetFollows
{
public:
    explicit AppBskyGraphGetFollowers(QObject *parent = nullptr);

    void getFollowers(const QString &actor, const int limit, const QString &cursor,
                      const QString &sort);
};

}

#endif // APPBSKYGRAPHGETFOLLOWERS_H
