// This file is generated by "defs2struct.py".
// Please do not edit.

#ifndef LEXICONS_FUNC_H
#define LEXICONS_FUNC_H

#include "lexicons.h"

#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QList>
#include <QString>
#include <QVariant>

namespace AppBskyActorDefs {
void copyProfileViewBasic(const QJsonObject &src, AppBskyActorDefs::ProfileViewBasic &dest);
}

#endif // LEXICONS_FUNC_H
