// This file is generated by "defs2struct.py".
// Please do not edit.

#ifndef LEXICONS_FUNC_CPP
#define LEXICONS_FUNC_CPP

#include "lexicons_func.h"

namespace AppBskyActorDefs {
void copyProfileViewBasic(const QJsonObject &src, AppBskyActorDefs::ProfileViewBasic &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
        dest.handle = src.value("handle").toString();
        dest.displayName = src.value("displayName").toString();
        dest.avatar = src.value("avatar").toString();
    // ref viewer
    // array labels
    }
}
}

#endif // LEXICONS_FUNC_CPP
