// This file is generated by "defs2struct.py".
// Please do not edit.

#ifndef LEXICONS_FUNC_CPP
#define LEXICONS_FUNC_CPP

#include "lexicons_func.h"
#include "lexicons_func_unknown.h"

namespace AtProtocolType {
// app.bsky.actor.defs
namespace AppBskyActorDefs {
void copyProfileAssociated(const QJsonObject &src, AppBskyActorDefs::ProfileAssociated &dest)
{
    if (!src.isEmpty()) {
        dest.lists = src.value("lists").toInt();
        dest.feedgens = src.value("feedgens").toInt();
        dest.labeler = src.value("labeler").toBool();
    }
}
void copyViewerState(const QJsonObject &src, AppBskyActorDefs::ViewerState &dest)
{
    if (!src.isEmpty()) {
        dest.muted = src.value("muted").toBool();
        AppBskyGraphDefs::copyListViewBasic(src.value("mutedByList").toObject(), dest.mutedByList);
        dest.blockedBy = src.value("blockedBy").toBool();
        dest.blocking = src.value("blocking").toString();
        AppBskyGraphDefs::copyListViewBasic(src.value("blockingByList").toObject(),
                                            dest.blockingByList);
        dest.following = src.value("following").toString();
        dest.followedBy = src.value("followedBy").toString();
    }
}
void copyProfileViewBasic(const QJsonObject &src, AppBskyActorDefs::ProfileViewBasic &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
        dest.handle = src.value("handle").toString();
        dest.displayName = src.value("displayName").toString();
        dest.avatar = src.value("avatar").toString();
        copyProfileAssociated(src.value("associated").toObject(), dest.associated);
        copyViewerState(src.value("viewer").toObject(), dest.viewer);
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
    }
}
void copyProfileView(const QJsonObject &src, AppBskyActorDefs::ProfileView &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
        dest.handle = src.value("handle").toString();
        dest.displayName = src.value("displayName").toString();
        dest.description = src.value("description").toString();
        dest.avatar = src.value("avatar").toString();
        copyProfileAssociated(src.value("associated").toObject(), dest.associated);
        dest.indexedAt = src.value("indexedAt").toString();
        copyViewerState(src.value("viewer").toObject(), dest.viewer);
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
    }
}
void copyProfileViewDetailed(const QJsonObject &src, AppBskyActorDefs::ProfileViewDetailed &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
        dest.handle = src.value("handle").toString();
        dest.displayName = src.value("displayName").toString();
        dest.description = src.value("description").toString();
        dest.avatar = src.value("avatar").toString();
        dest.banner = src.value("banner").toString();
        dest.followersCount = src.value("followersCount").toInt();
        dest.followsCount = src.value("followsCount").toInt();
        dest.postsCount = src.value("postsCount").toInt();
        copyProfileAssociated(src.value("associated").toObject(), dest.associated);
        dest.indexedAt = src.value("indexedAt").toString();
        copyViewerState(src.value("viewer").toObject(), dest.viewer);
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
    }
}
void copyAdultContentPref(const QJsonObject &src, AppBskyActorDefs::AdultContentPref &dest)
{
    if (!src.isEmpty()) {
        dest.enabled = src.value("enabled").toBool();
    }
}
void copyContentLabelPref(const QJsonObject &src, AppBskyActorDefs::ContentLabelPref &dest)
{
    if (!src.isEmpty()) {
        dest.labelerDid = src.value("labelerDid").toString();
        dest.label = src.value("label").toString();
        dest.visibility = src.value("visibility").toString();
    }
}
void copySavedFeedsPref(const QJsonObject &src, AppBskyActorDefs::SavedFeedsPref &dest)
{
    if (!src.isEmpty()) {
        for (const auto &value : src.value("pinned").toArray()) {
            dest.pinned.append(value.toString());
        }
        for (const auto &value : src.value("saved").toArray()) {
            dest.saved.append(value.toString());
        }
        dest.timelineIndex = src.value("timelineIndex").toInt();
    }
}
void copySavedFeed(const QJsonObject &src, AppBskyActorDefs::SavedFeed &dest)
{
    if (!src.isEmpty()) {
        dest.id = src.value("id").toString();
        dest.type = src.value("type").toString();
        dest.value = src.value("value").toString();
        dest.pinned = src.value("pinned").toBool();
    }
}
void copySavedFeedsPrefV2(const QJsonObject &src, AppBskyActorDefs::SavedFeedsPrefV2 &dest)
{
    if (!src.isEmpty()) {
        for (const auto &s : src.value("items").toArray()) {
            AppBskyActorDefs::SavedFeed child;
            AppBskyActorDefs::copySavedFeed(s.toObject(), child);
            dest.items.append(child);
        }
    }
}
void copyPersonalDetailsPref(const QJsonObject &src, AppBskyActorDefs::PersonalDetailsPref &dest)
{
    if (!src.isEmpty()) {
        dest.birthDate = src.value("birthDate").toString();
    }
}
void copyFeedViewPref(const QJsonObject &src, AppBskyActorDefs::FeedViewPref &dest)
{
    if (!src.isEmpty()) {
        dest.feed = src.value("feed").toString();
        dest.hideReplies = src.value("hideReplies").toBool();
        dest.hideRepliesByUnfollowed = src.value("hideRepliesByUnfollowed").toBool();
        dest.hideRepliesByLikeCount = src.value("hideRepliesByLikeCount").toInt();
        dest.hideReposts = src.value("hideReposts").toBool();
        dest.hideQuotePosts = src.value("hideQuotePosts").toBool();
    }
}
void copyThreadViewPref(const QJsonObject &src, AppBskyActorDefs::ThreadViewPref &dest)
{
    if (!src.isEmpty()) {
        dest.sort = src.value("sort").toString();
        dest.prioritizeFollowedUsers = src.value("prioritizeFollowedUsers").toBool();
    }
}
void copyInterestsPref(const QJsonObject &src, AppBskyActorDefs::InterestsPref &dest)
{
    if (!src.isEmpty()) {
        for (const auto &value : src.value("tags").toArray()) {
            dest.tags.append(value.toString());
        }
    }
}
void copyMutedWordTarget(const QJsonValue &src, AppBskyActorDefs::MutedWordTarget &dest)
{
    dest = src.toString();
}
void copyMutedWord(const QJsonObject &src, AppBskyActorDefs::MutedWord &dest)
{
    if (!src.isEmpty()) {
        dest.value = src.value("value").toString();
        for (const auto &s : src.value("targets").toArray()) {
            AppBskyActorDefs::MutedWordTarget child;
            AppBskyActorDefs::copyMutedWordTarget(s, child);
            dest.targets.append(child);
        }
    }
}
void copyMutedWordsPref(const QJsonObject &src, AppBskyActorDefs::MutedWordsPref &dest)
{
    if (!src.isEmpty()) {
        for (const auto &s : src.value("items").toArray()) {
            AppBskyActorDefs::MutedWord child;
            AppBskyActorDefs::copyMutedWord(s.toObject(), child);
            dest.items.append(child);
        }
    }
}
void copyHiddenPostsPref(const QJsonObject &src, AppBskyActorDefs::HiddenPostsPref &dest)
{
    if (!src.isEmpty()) {
        for (const auto &value : src.value("items").toArray()) {
            dest.items.append(value.toString());
        }
    }
}
void copyLabelerPrefItem(const QJsonObject &src, AppBskyActorDefs::LabelerPrefItem &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
    }
}
void copyLabelersPref(const QJsonObject &src, AppBskyActorDefs::LabelersPref &dest)
{
    if (!src.isEmpty()) {
        for (const auto &s : src.value("labelers").toArray()) {
            LabelerPrefItem child;
            copyLabelerPrefItem(s.toObject(), child);
            dest.labelers.append(child);
        }
    }
}
void copyPreferences(const QJsonArray &src, AppBskyActorDefs::Preferences &dest)
{
    if (!src.isEmpty()) {
        for (const auto &value : src) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.actor.defs#adultContentPref")) {
                AppBskyActorDefs::AdultContentPref child;
                AppBskyActorDefs::copyAdultContentPref(value.toObject(), child);
                dest.adultContentPref.append(child);
            } else if (value_type == QStringLiteral("app.bsky.actor.defs#contentLabelPref")) {
                AppBskyActorDefs::ContentLabelPref child;
                AppBskyActorDefs::copyContentLabelPref(value.toObject(), child);
                dest.contentLabelPref.append(child);
            } else if (value_type == QStringLiteral("app.bsky.actor.defs#savedFeedsPref")) {
                AppBskyActorDefs::SavedFeedsPref child;
                AppBskyActorDefs::copySavedFeedsPref(value.toObject(), child);
                dest.savedFeedsPref.append(child);
            } else if (value_type == QStringLiteral("app.bsky.actor.defs#savedFeedsPrefV2")) {
                AppBskyActorDefs::SavedFeedsPrefV2 child;
                AppBskyActorDefs::copySavedFeedsPrefV2(value.toObject(), child);
                dest.savedFeedsPrefV2.append(child);
            } else if (value_type == QStringLiteral("app.bsky.actor.defs#personalDetailsPref")) {
                AppBskyActorDefs::PersonalDetailsPref child;
                AppBskyActorDefs::copyPersonalDetailsPref(value.toObject(), child);
                dest.personalDetailsPref.append(child);
            } else if (value_type == QStringLiteral("app.bsky.actor.defs#feedViewPref")) {
                AppBskyActorDefs::FeedViewPref child;
                AppBskyActorDefs::copyFeedViewPref(value.toObject(), child);
                dest.feedViewPref.append(child);
            } else if (value_type == QStringLiteral("app.bsky.actor.defs#threadViewPref")) {
                AppBskyActorDefs::ThreadViewPref child;
                AppBskyActorDefs::copyThreadViewPref(value.toObject(), child);
                dest.threadViewPref.append(child);
            } else if (value_type == QStringLiteral("app.bsky.actor.defs#interestsPref")) {
                AppBskyActorDefs::InterestsPref child;
                AppBskyActorDefs::copyInterestsPref(value.toObject(), child);
                dest.interestsPref.append(child);
            } else if (value_type == QStringLiteral("app.bsky.actor.defs#mutedWordsPref")) {
                AppBskyActorDefs::MutedWordsPref child;
                AppBskyActorDefs::copyMutedWordsPref(value.toObject(), child);
                dest.mutedWordsPref.append(child);
            } else if (value_type == QStringLiteral("app.bsky.actor.defs#hiddenPostsPref")) {
                AppBskyActorDefs::HiddenPostsPref child;
                AppBskyActorDefs::copyHiddenPostsPref(value.toObject(), child);
                dest.hiddenPostsPref.append(child);
            } else if (value_type == QStringLiteral("app.bsky.actor.defs#labelersPref")) {
                AppBskyActorDefs::LabelersPref child;
                AppBskyActorDefs::copyLabelersPref(value.toObject(), child);
                dest.labelersPref.append(child);
            }
        }
    }
}
}
// app.bsky.graph.defs
namespace AppBskyGraphDefs {
void copyListPurpose(const QJsonValue &src, AppBskyGraphDefs::ListPurpose &dest)
{
    dest = src.toString();
}
void copyListViewerState(const QJsonObject &src, AppBskyGraphDefs::ListViewerState &dest)
{
    if (!src.isEmpty()) {
        dest.muted = src.value("muted").toBool();
        dest.blocked = src.value("blocked").toString();
    }
}
void copyListViewBasic(const QJsonObject &src, AppBskyGraphDefs::ListViewBasic &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        dest.name = src.value("name").toString();
        copyListPurpose(src.value("purpose"), dest.purpose);
        dest.avatar = src.value("avatar").toString();
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
        copyListViewerState(src.value("viewer").toObject(), dest.viewer);
        dest.indexedAt = src.value("indexedAt").toString();
    }
}
void copyListView(const QJsonObject &src, AppBskyGraphDefs::ListView &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        if (dest.creator.isNull())
            dest.creator = QSharedPointer<AppBskyActorDefs::ProfileView>(
                    new AppBskyActorDefs::ProfileView());
        AppBskyActorDefs::copyProfileView(src.value("creator").toObject(), *dest.creator);
        dest.name = src.value("name").toString();
        copyListPurpose(src.value("purpose"), dest.purpose);
        dest.description = src.value("description").toString();
        for (const auto &s : src.value("descriptionFacets").toArray()) {
            QSharedPointer<AppBskyRichtextFacet::Main> child =
                    QSharedPointer<AppBskyRichtextFacet::Main>(new AppBskyRichtextFacet::Main());
            AppBskyRichtextFacet::copyMain(s.toObject(), *child);
            dest.descriptionFacets.append(child);
        }
        dest.avatar = src.value("avatar").toString();
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
        copyListViewerState(src.value("viewer").toObject(), dest.viewer);
        dest.indexedAt = src.value("indexedAt").toString();
    }
}
void copyListItemView(const QJsonObject &src, AppBskyGraphDefs::ListItemView &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        if (dest.subject.isNull())
            dest.subject = QSharedPointer<AppBskyActorDefs::ProfileView>(
                    new AppBskyActorDefs::ProfileView());
        AppBskyActorDefs::copyProfileView(src.value("subject").toObject(), *dest.subject);
    }
}
void copyNotFoundActor(const QJsonObject &src, AppBskyGraphDefs::NotFoundActor &dest)
{
    if (!src.isEmpty()) {
        dest.actor = src.value("actor").toString();
        dest.notFound = src.value("notFound").toBool();
    }
}
void copyRelationship(const QJsonObject &src, AppBskyGraphDefs::Relationship &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
        dest.following = src.value("following").toString();
        dest.followedBy = src.value("followedBy").toString();
    }
}
}
// com.atproto.label.defs
namespace ComAtprotoLabelDefs {
void copyLabel(const QJsonObject &src, ComAtprotoLabelDefs::Label &dest)
{
    if (!src.isEmpty()) {
        dest.ver = src.value("ver").toInt();
        dest.src = src.value("src").toString();
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        dest.val = src.value("val").toString();
        dest.neg = src.value("neg").toBool();
        dest.cts = src.value("cts").toString();
        dest.exp = src.value("exp").toString();
    }
}
void copySelfLabel(const QJsonObject &src, ComAtprotoLabelDefs::SelfLabel &dest)
{
    if (!src.isEmpty()) {
        dest.val = src.value("val").toString();
    }
}
void copySelfLabels(const QJsonObject &src, ComAtprotoLabelDefs::SelfLabels &dest)
{
    if (!src.isEmpty()) {
        for (const auto &s : src.value("values").toArray()) {
            SelfLabel child;
            copySelfLabel(s.toObject(), child);
            dest.values.append(child);
        }
    }
}
void copyLabelValue(const QJsonValue &src, ComAtprotoLabelDefs::LabelValue &dest)
{
    dest = src.toString();
}
void copyLabelValueDefinitionStrings(const QJsonObject &src,
                                     ComAtprotoLabelDefs::LabelValueDefinitionStrings &dest)
{
    if (!src.isEmpty()) {
        dest.lang = src.value("lang").toString();
        dest.name = src.value("name").toString();
        dest.description = src.value("description").toString();
    }
}
void copyLabelValueDefinition(const QJsonObject &src,
                              ComAtprotoLabelDefs::LabelValueDefinition &dest)
{
    if (!src.isEmpty()) {
        dest.identifier = src.value("identifier").toString();
        dest.severity = src.value("severity").toString();
        dest.blurs = src.value("blurs").toString();
        dest.defaultSetting = src.value("defaultSetting").toString();
        dest.adultOnly = src.value("adultOnly").toBool();
        for (const auto &s : src.value("locales").toArray()) {
            LabelValueDefinitionStrings child;
            copyLabelValueDefinitionStrings(s.toObject(), child);
            dest.locales.append(child);
        }
    }
}
}
// app.bsky.actor.profile
namespace AppBskyActorProfile {
void copyMain(const QJsonObject &src, AppBskyActorProfile::Main &dest)
{
    if (!src.isEmpty()) {
        dest.displayName = src.value("displayName").toString();
        dest.description = src.value("description").toString();
        LexiconsTypeUnknown::copyBlob(src.value("avatar").toObject(), dest.avatar);
        LexiconsTypeUnknown::copyBlob(src.value("banner").toObject(), dest.banner);
        QString labels_type = src.value("labels").toObject().value("$type").toString();
        if (labels_type == QStringLiteral("com.atproto.label.defs#selfLabels")) {
            dest.labels_type =
                    AppBskyActorProfile::MainLabelsType::labels_ComAtprotoLabelDefs_SelfLabels;
            ComAtprotoLabelDefs::copySelfLabels(src.value("labels").toObject(),
                                                dest.labels_ComAtprotoLabelDefs_SelfLabels);
        }
        dest.pinnedPost = src.value("pinnedPost").toString();
    }
}
}
// app.bsky.embed.external
namespace AppBskyEmbedExternal {
void copyExternal(const QJsonObject &src, AppBskyEmbedExternal::External &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.title = src.value("title").toString();
        dest.description = src.value("description").toString();
        LexiconsTypeUnknown::copyBlob(src.value("thumb").toObject(), dest.thumb);
    }
}
void copyMain(const QJsonObject &src, AppBskyEmbedExternal::Main &dest)
{
    if (!src.isEmpty()) {
        copyExternal(src.value("external").toObject(), dest.external);
    }
}
void copyViewExternal(const QJsonObject &src, AppBskyEmbedExternal::ViewExternal &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.title = src.value("title").toString();
        dest.description = src.value("description").toString();
        dest.thumb = src.value("thumb").toString();
    }
}
void copyView(const QJsonObject &src, AppBskyEmbedExternal::View &dest)
{
    if (!src.isEmpty()) {
        copyViewExternal(src.value("external").toObject(), dest.external);
    }
}
}
// app.bsky.embed.images
namespace AppBskyEmbedImages {
void copyAspectRatio(const QJsonObject &src, AppBskyEmbedImages::AspectRatio &dest)
{
    if (!src.isEmpty()) {
        dest.width = src.value("width").toInt();
        dest.height = src.value("height").toInt();
    }
}
void copyImage(const QJsonObject &src, AppBskyEmbedImages::Image &dest)
{
    if (!src.isEmpty()) {
        LexiconsTypeUnknown::copyBlob(src.value("image").toObject(), dest.image);
        dest.alt = src.value("alt").toString();
        copyAspectRatio(src.value("aspectRatio").toObject(), dest.aspectRatio);
    }
}
void copyMain(const QJsonObject &src, AppBskyEmbedImages::Main &dest)
{
    if (!src.isEmpty()) {
        for (const auto &s : src.value("images").toArray()) {
            Image child;
            copyImage(s.toObject(), child);
            dest.images.append(child);
        }
    }
}
void copyViewImage(const QJsonObject &src, AppBskyEmbedImages::ViewImage &dest)
{
    if (!src.isEmpty()) {
        dest.thumb = src.value("thumb").toString();
        dest.fullsize = src.value("fullsize").toString();
        dest.alt = src.value("alt").toString();
        copyAspectRatio(src.value("aspectRatio").toObject(), dest.aspectRatio);
    }
}
void copyView(const QJsonObject &src, AppBskyEmbedImages::View &dest)
{
    if (!src.isEmpty()) {
        for (const auto &s : src.value("images").toArray()) {
            ViewImage child;
            copyViewImage(s.toObject(), child);
            dest.images.append(child);
        }
    }
}
}
// com.atproto.repo.strongRef
namespace ComAtprotoRepoStrongRef {
void copyMain(const QJsonObject &src, ComAtprotoRepoStrongRef::Main &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
    }
}
}
// app.bsky.embed.record
namespace AppBskyEmbedRecord {
void copyMain(const QJsonObject &src, AppBskyEmbedRecord::Main &dest)
{
    if (!src.isEmpty()) {
        ComAtprotoRepoStrongRef::copyMain(src.value("record").toObject(), dest.record);
    }
}
void copyViewRecord(const QJsonObject &src, AppBskyEmbedRecord::ViewRecord &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        AppBskyActorDefs::copyProfileViewBasic(src.value("author").toObject(), dest.author);
        LexiconsTypeUnknown::copyUnknown(src.value("value").toObject(), dest.value);
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
        dest.replyCount = src.value("replyCount").toInt();
        dest.repostCount = src.value("repostCount").toInt();
        dest.likeCount = src.value("likeCount").toInt();
        // array<union> embeds
        for (const auto &value : src.value("embeds").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.embed.images#view")) {
                AppBskyEmbedImages::View child;
                AppBskyEmbedImages::copyView(value.toObject(), child);
                dest.embeds_AppBskyEmbedImages_View.append(child);
            }
        }
        for (const auto &value : src.value("embeds").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.embed.external#view")) {
                AppBskyEmbedExternal::View child;
                AppBskyEmbedExternal::copyView(value.toObject(), child);
                dest.embeds_AppBskyEmbedExternal_View.append(child);
            }
        }
        for (const auto &value : src.value("embeds").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.embed.record#view")) {
                QSharedPointer<AppBskyEmbedRecord::View> child =
                        QSharedPointer<AppBskyEmbedRecord::View>(new AppBskyEmbedRecord::View());
                AppBskyEmbedRecord::copyView(value.toObject(), *child);
                dest.embeds_AppBskyEmbedRecord_View.append(child);
            }
        }
        for (const auto &value : src.value("embeds").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.embed.recordWithMedia#view")) {
                AppBskyEmbedRecordWithMedia::View child;
                AppBskyEmbedRecordWithMedia::copyView(value.toObject(), child);
                dest.embeds_AppBskyEmbedRecordWithMedia_View.append(child);
            }
        }
        dest.indexedAt = src.value("indexedAt").toString();
    }
}
void copyViewNotFound(const QJsonObject &src, AppBskyEmbedRecord::ViewNotFound &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.notFound = src.value("notFound").toBool();
    }
}
void copyViewBlocked(const QJsonObject &src, AppBskyEmbedRecord::ViewBlocked &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.blocked = src.value("blocked").toBool();
        AppBskyFeedDefs::copyBlockedAuthor(src.value("author").toObject(), dest.author);
    }
}
void copyView(const QJsonObject &src, AppBskyEmbedRecord::View &dest)
{
    if (!src.isEmpty()) {
        QString record_type = src.value("record").toObject().value("$type").toString();
        if (record_type == QStringLiteral("app.bsky.embed.record#viewRecord")) {
            dest.record_type = AppBskyEmbedRecord::ViewRecordType::record_ViewRecord;
            AppBskyEmbedRecord::copyViewRecord(src.value("record").toObject(),
                                               dest.record_ViewRecord);
        }
        if (record_type == QStringLiteral("app.bsky.embed.record#viewNotFound")) {
            dest.record_type = AppBskyEmbedRecord::ViewRecordType::record_ViewNotFound;
            AppBskyEmbedRecord::copyViewNotFound(src.value("record").toObject(),
                                                 dest.record_ViewNotFound);
        }
        if (record_type == QStringLiteral("app.bsky.embed.record#viewBlocked")) {
            dest.record_type = AppBskyEmbedRecord::ViewRecordType::record_ViewBlocked;
            AppBskyEmbedRecord::copyViewBlocked(src.value("record").toObject(),
                                                dest.record_ViewBlocked);
        }
        if (record_type == QStringLiteral("app.bsky.feed.defs#generatorView")) {
            dest.record_type =
                    AppBskyEmbedRecord::ViewRecordType::record_AppBskyFeedDefs_GeneratorView;
            AppBskyFeedDefs::copyGeneratorView(src.value("record").toObject(),
                                               dest.record_AppBskyFeedDefs_GeneratorView);
        }
        if (record_type == QStringLiteral("app.bsky.graph.defs#listView")) {
            dest.record_type = AppBskyEmbedRecord::ViewRecordType::record_AppBskyGraphDefs_ListView;
            AppBskyGraphDefs::copyListView(src.value("record").toObject(),
                                           dest.record_AppBskyGraphDefs_ListView);
        }
        if (record_type == QStringLiteral("app.bsky.labeler.defs#labelerView")) {
            dest.record_type =
                    AppBskyEmbedRecord::ViewRecordType::record_AppBskyLabelerDefs_LabelerView;
            AppBskyLabelerDefs::copyLabelerView(src.value("record").toObject(),
                                                dest.record_AppBskyLabelerDefs_LabelerView);
        }
    }
}
}
// app.bsky.embed.recordWithMedia
namespace AppBskyEmbedRecordWithMedia {
void copyView(const QJsonObject &src, AppBskyEmbedRecordWithMedia::View &dest)
{
    if (!src.isEmpty()) {
        if (dest.record.isNull())
            dest.record = QSharedPointer<AppBskyEmbedRecord::View>(new AppBskyEmbedRecord::View());
        AppBskyEmbedRecord::copyView(src.value("record").toObject(), *dest.record);
        QString media_type = src.value("media").toObject().value("$type").toString();
        if (media_type == QStringLiteral("app.bsky.embed.images#view")) {
            dest.media_type =
                    AppBskyEmbedRecordWithMedia::ViewMediaType::media_AppBskyEmbedImages_View;
            AppBskyEmbedImages::copyView(src.value("media").toObject(),
                                         dest.media_AppBskyEmbedImages_View);
        }
        if (media_type == QStringLiteral("app.bsky.embed.external#view")) {
            dest.media_type =
                    AppBskyEmbedRecordWithMedia::ViewMediaType::media_AppBskyEmbedExternal_View;
            AppBskyEmbedExternal::copyView(src.value("media").toObject(),
                                           dest.media_AppBskyEmbedExternal_View);
        }
    }
}
void copyMain(const QJsonObject &src, AppBskyEmbedRecordWithMedia::Main &dest)
{
    if (!src.isEmpty()) {
        if (dest.record.isNull())
            dest.record = QSharedPointer<AppBskyEmbedRecord::Main>(new AppBskyEmbedRecord::Main());
        AppBskyEmbedRecord::copyMain(src.value("record").toObject(), *dest.record);
        QString media_type = src.value("media").toObject().value("$type").toString();
        if (media_type == QStringLiteral("app.bsky.embed.images")) {
            dest.media_type =
                    AppBskyEmbedRecordWithMedia::MainMediaType::media_AppBskyEmbedImages_Main;
            AppBskyEmbedImages::copyMain(src.value("media").toObject(),
                                         dest.media_AppBskyEmbedImages_Main);
        }
        if (media_type == QStringLiteral("app.bsky.embed.external")) {
            dest.media_type =
                    AppBskyEmbedRecordWithMedia::MainMediaType::media_AppBskyEmbedExternal_Main;
            AppBskyEmbedExternal::copyMain(src.value("media").toObject(),
                                           dest.media_AppBskyEmbedExternal_Main);
        }
    }
}
}
// app.bsky.feed.defs
namespace AppBskyFeedDefs {
void copyBlockedAuthor(const QJsonObject &src, AppBskyFeedDefs::BlockedAuthor &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
        AppBskyActorDefs::copyViewerState(src.value("viewer").toObject(), dest.viewer);
    }
}
void copyGeneratorViewerState(const QJsonObject &src, AppBskyFeedDefs::GeneratorViewerState &dest)
{
    if (!src.isEmpty()) {
        dest.like = src.value("like").toString();
    }
}
void copyGeneratorView(const QJsonObject &src, AppBskyFeedDefs::GeneratorView &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        dest.did = src.value("did").toString();
        AppBskyActorDefs::copyProfileView(src.value("creator").toObject(), dest.creator);
        dest.displayName = src.value("displayName").toString();
        dest.description = src.value("description").toString();
        for (const auto &s : src.value("descriptionFacets").toArray()) {
            AppBskyRichtextFacet::Main child;
            AppBskyRichtextFacet::copyMain(s.toObject(), child);
            dest.descriptionFacets.append(child);
        }
        dest.avatar = src.value("avatar").toString();
        dest.likeCount = src.value("likeCount").toInt();
        dest.acceptsInteractions = src.value("acceptsInteractions").toBool();
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
        copyGeneratorViewerState(src.value("viewer").toObject(), dest.viewer);
        dest.indexedAt = src.value("indexedAt").toString();
    }
}
void copyViewerState(const QJsonObject &src, AppBskyFeedDefs::ViewerState &dest)
{
    if (!src.isEmpty()) {
        dest.repost = src.value("repost").toString();
        dest.like = src.value("like").toString();
        dest.replyDisabled = src.value("replyDisabled").toBool();
    }
}
void copyThreadgateView(const QJsonObject &src, AppBskyFeedDefs::ThreadgateView &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        LexiconsTypeUnknown::copyUnknown(src.value("record").toObject(), dest.record);
        for (const auto &s : src.value("lists").toArray()) {
            AppBskyGraphDefs::ListViewBasic child;
            AppBskyGraphDefs::copyListViewBasic(s.toObject(), child);
            dest.lists.append(child);
        }
    }
}
void copyPostView(const QJsonObject &src, AppBskyFeedDefs::PostView &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        AppBskyActorDefs::copyProfileViewBasic(src.value("author").toObject(), dest.author);
        LexiconsTypeUnknown::copyUnknown(src.value("record").toObject(), dest.record);
        QString embed_type = src.value("embed").toObject().value("$type").toString();
        if (embed_type == QStringLiteral("app.bsky.embed.images#view")) {
            dest.embed_type = AppBskyFeedDefs::PostViewEmbedType::embed_AppBskyEmbedImages_View;
            AppBskyEmbedImages::copyView(src.value("embed").toObject(),
                                         dest.embed_AppBskyEmbedImages_View);
        }
        if (embed_type == QStringLiteral("app.bsky.embed.external#view")) {
            dest.embed_type = AppBskyFeedDefs::PostViewEmbedType::embed_AppBskyEmbedExternal_View;
            AppBskyEmbedExternal::copyView(src.value("embed").toObject(),
                                           dest.embed_AppBskyEmbedExternal_View);
        }
        // union *embed app.bsky.embed.record#view
        if (embed_type == QStringLiteral("app.bsky.embed.record#view")) {
            dest.embed_type = AppBskyFeedDefs::PostViewEmbedType::embed_AppBskyEmbedRecord_View;
            if (dest.embed_AppBskyEmbedRecord_View.isNull())
                dest.embed_AppBskyEmbedRecord_View =
                        QSharedPointer<AppBskyEmbedRecord::View>(new AppBskyEmbedRecord::View());
            AppBskyEmbedRecord::copyView(src.value("embed").toObject(),
                                         *dest.embed_AppBskyEmbedRecord_View);
        }
        if (embed_type == QStringLiteral("app.bsky.embed.recordWithMedia#view")) {
            dest.embed_type =
                    AppBskyFeedDefs::PostViewEmbedType::embed_AppBskyEmbedRecordWithMedia_View;
            AppBskyEmbedRecordWithMedia::copyView(src.value("embed").toObject(),
                                                  dest.embed_AppBskyEmbedRecordWithMedia_View);
        }
        dest.replyCount = src.value("replyCount").toInt();
        dest.repostCount = src.value("repostCount").toInt();
        dest.likeCount = src.value("likeCount").toInt();
        dest.indexedAt = src.value("indexedAt").toString();
        copyViewerState(src.value("viewer").toObject(), dest.viewer);
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
        copyThreadgateView(src.value("threadgate").toObject(), dest.threadgate);
    }
}
void copyNotFoundPost(const QJsonObject &src, AppBskyFeedDefs::NotFoundPost &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.notFound = src.value("notFound").toBool();
    }
}
void copyBlockedPost(const QJsonObject &src, AppBskyFeedDefs::BlockedPost &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.blocked = src.value("blocked").toBool();
        copyBlockedAuthor(src.value("author").toObject(), dest.author);
    }
}
void copyReplyRef(const QJsonObject &src, AppBskyFeedDefs::ReplyRef &dest)
{
    if (!src.isEmpty()) {
        QString root_type = src.value("root").toObject().value("$type").toString();
        if (root_type == QStringLiteral("app.bsky.feed.defs#postView")) {
            dest.root_type = AppBskyFeedDefs::ReplyRefRootType::root_PostView;
            AppBskyFeedDefs::copyPostView(src.value("root").toObject(), dest.root_PostView);
        }
        if (root_type == QStringLiteral("app.bsky.feed.defs#notFoundPost")) {
            dest.root_type = AppBskyFeedDefs::ReplyRefRootType::root_NotFoundPost;
            AppBskyFeedDefs::copyNotFoundPost(src.value("root").toObject(), dest.root_NotFoundPost);
        }
        if (root_type == QStringLiteral("app.bsky.feed.defs#blockedPost")) {
            dest.root_type = AppBskyFeedDefs::ReplyRefRootType::root_BlockedPost;
            AppBskyFeedDefs::copyBlockedPost(src.value("root").toObject(), dest.root_BlockedPost);
        }
        QString parent_type = src.value("parent").toObject().value("$type").toString();
        if (parent_type == QStringLiteral("app.bsky.feed.defs#postView")) {
            dest.parent_type = AppBskyFeedDefs::ReplyRefParentType::parent_PostView;
            AppBskyFeedDefs::copyPostView(src.value("parent").toObject(), dest.parent_PostView);
        }
        if (parent_type == QStringLiteral("app.bsky.feed.defs#notFoundPost")) {
            dest.parent_type = AppBskyFeedDefs::ReplyRefParentType::parent_NotFoundPost;
            AppBskyFeedDefs::copyNotFoundPost(src.value("parent").toObject(),
                                              dest.parent_NotFoundPost);
        }
        if (parent_type == QStringLiteral("app.bsky.feed.defs#blockedPost")) {
            dest.parent_type = AppBskyFeedDefs::ReplyRefParentType::parent_BlockedPost;
            AppBskyFeedDefs::copyBlockedPost(src.value("parent").toObject(),
                                             dest.parent_BlockedPost);
        }
    }
}
void copyReasonRepost(const QJsonObject &src, AppBskyFeedDefs::ReasonRepost &dest)
{
    if (!src.isEmpty()) {
        AppBskyActorDefs::copyProfileViewBasic(src.value("by").toObject(), dest.by);
        dest.indexedAt = src.value("indexedAt").toString();
    }
}
void copyFeedViewPost(const QJsonObject &src, AppBskyFeedDefs::FeedViewPost &dest)
{
    if (!src.isEmpty()) {
        copyPostView(src.value("post").toObject(), dest.post);
        copyReplyRef(src.value("reply").toObject(), dest.reply);
        QString reason_type = src.value("reason").toObject().value("$type").toString();
        if (reason_type == QStringLiteral("app.bsky.feed.defs#reasonRepost")) {
            dest.reason_type = AppBskyFeedDefs::FeedViewPostReasonType::reason_ReasonRepost;
            AppBskyFeedDefs::copyReasonRepost(src.value("reason").toObject(),
                                              dest.reason_ReasonRepost);
        }
        dest.feedContext = src.value("feedContext").toString();
    }
}
void copyThreadViewPost(const QJsonObject &src, AppBskyFeedDefs::ThreadViewPost &dest)
{
    if (!src.isEmpty()) {
        copyPostView(src.value("post").toObject(), dest.post);
        QString parent_type = src.value("parent").toObject().value("$type").toString();
        // union *parent #threadViewPost
        if (parent_type == QStringLiteral("app.bsky.feed.defs#threadViewPost")) {
            dest.parent_type = AppBskyFeedDefs::ThreadViewPostParentType::parent_ThreadViewPost;
            if (dest.parent_ThreadViewPost.isNull())
                dest.parent_ThreadViewPost = QSharedPointer<AppBskyFeedDefs::ThreadViewPost>(
                        new AppBskyFeedDefs::ThreadViewPost());
            AppBskyFeedDefs::copyThreadViewPost(src.value("parent").toObject(),
                                                *dest.parent_ThreadViewPost);
        }
        if (parent_type == QStringLiteral("app.bsky.feed.defs#notFoundPost")) {
            dest.parent_type = AppBskyFeedDefs::ThreadViewPostParentType::parent_NotFoundPost;
            AppBskyFeedDefs::copyNotFoundPost(src.value("parent").toObject(),
                                              dest.parent_NotFoundPost);
        }
        if (parent_type == QStringLiteral("app.bsky.feed.defs#blockedPost")) {
            dest.parent_type = AppBskyFeedDefs::ThreadViewPostParentType::parent_BlockedPost;
            AppBskyFeedDefs::copyBlockedPost(src.value("parent").toObject(),
                                             dest.parent_BlockedPost);
        }
        // array<union> replies
        for (const auto &value : src.value("replies").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.feed.defs#threadViewPost")) {
                QSharedPointer<AppBskyFeedDefs::ThreadViewPost> child =
                        QSharedPointer<AppBskyFeedDefs::ThreadViewPost>(
                                new AppBskyFeedDefs::ThreadViewPost());
                AppBskyFeedDefs::copyThreadViewPost(value.toObject(), *child);
                dest.replies_ThreadViewPost.append(child);
            }
        }
        for (const auto &value : src.value("replies").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.feed.defs#notFoundPost")) {
                AppBskyFeedDefs::NotFoundPost child;
                AppBskyFeedDefs::copyNotFoundPost(value.toObject(), child);
                dest.replies_NotFoundPost.append(child);
            }
        }
        for (const auto &value : src.value("replies").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.feed.defs#blockedPost")) {
                AppBskyFeedDefs::BlockedPost child;
                AppBskyFeedDefs::copyBlockedPost(value.toObject(), child);
                dest.replies_BlockedPost.append(child);
            }
        }
    }
}
void copySkeletonReasonRepost(const QJsonObject &src, AppBskyFeedDefs::SkeletonReasonRepost &dest)
{
    if (!src.isEmpty()) {
        dest.repost = src.value("repost").toString();
    }
}
void copySkeletonFeedPost(const QJsonObject &src, AppBskyFeedDefs::SkeletonFeedPost &dest)
{
    if (!src.isEmpty()) {
        dest.post = src.value("post").toString();
        QString reason_type = src.value("reason").toObject().value("$type").toString();
        if (reason_type == QStringLiteral("app.bsky.feed.defs#skeletonReasonRepost")) {
            dest.reason_type =
                    AppBskyFeedDefs::SkeletonFeedPostReasonType::reason_SkeletonReasonRepost;
            AppBskyFeedDefs::copySkeletonReasonRepost(src.value("reason").toObject(),
                                                      dest.reason_SkeletonReasonRepost);
        }
        dest.feedContext = src.value("feedContext").toString();
    }
}
void copyInteraction(const QJsonObject &src, AppBskyFeedDefs::Interaction &dest)
{
    if (!src.isEmpty()) {
        dest.item = src.value("item").toString();
        dest.event = src.value("event").toString();
        dest.feedContext = src.value("feedContext").toString();
    }
}
}
// app.bsky.richtext.facet
namespace AppBskyRichtextFacet {
void copyByteSlice(const QJsonObject &src, AppBskyRichtextFacet::ByteSlice &dest)
{
    if (!src.isEmpty()) {
        dest.byteStart = src.value("byteStart").toInt();
        dest.byteEnd = src.value("byteEnd").toInt();
    }
}
void copyMention(const QJsonObject &src, AppBskyRichtextFacet::Mention &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
    }
}
void copyLink(const QJsonObject &src, AppBskyRichtextFacet::Link &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
    }
}
void copyTag(const QJsonObject &src, AppBskyRichtextFacet::Tag &dest)
{
    if (!src.isEmpty()) {
        dest.tag = src.value("tag").toString();
    }
}
void copyMain(const QJsonObject &src, AppBskyRichtextFacet::Main &dest)
{
    if (!src.isEmpty()) {
        copyByteSlice(src.value("index").toObject(), dest.index);
        // array<union> features
        for (const auto &value : src.value("features").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.richtext.facet#mention")) {
                AppBskyRichtextFacet::Mention child;
                AppBskyRichtextFacet::copyMention(value.toObject(), child);
                dest.features_Mention.append(child);
            }
        }
        for (const auto &value : src.value("features").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.richtext.facet#link")) {
                AppBskyRichtextFacet::Link child;
                AppBskyRichtextFacet::copyLink(value.toObject(), child);
                dest.features_Link.append(child);
            }
        }
        for (const auto &value : src.value("features").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.richtext.facet#tag")) {
                AppBskyRichtextFacet::Tag child;
                AppBskyRichtextFacet::copyTag(value.toObject(), child);
                dest.features_Tag.append(child);
            }
        }
    }
}
}
// app.bsky.labeler.defs
namespace AppBskyLabelerDefs {
void copyLabelerViewerState(const QJsonObject &src, AppBskyLabelerDefs::LabelerViewerState &dest)
{
    if (!src.isEmpty()) {
        dest.like = src.value("like").toString();
    }
}
void copyLabelerView(const QJsonObject &src, AppBskyLabelerDefs::LabelerView &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        AppBskyActorDefs::copyProfileView(src.value("creator").toObject(), dest.creator);
        dest.likeCount = src.value("likeCount").toInt();
        copyLabelerViewerState(src.value("viewer").toObject(), dest.viewer);
        dest.indexedAt = src.value("indexedAt").toString();
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
    }
}
void copyLabelerPolicies(const QJsonObject &src, AppBskyLabelerDefs::LabelerPolicies &dest)
{
    if (!src.isEmpty()) {
        for (const auto &s : src.value("labelValues").toArray()) {
            ComAtprotoLabelDefs::LabelValue child;
            ComAtprotoLabelDefs::copyLabelValue(s, child);
            dest.labelValues.append(child);
        }
        for (const auto &s : src.value("labelValueDefinitions").toArray()) {
            ComAtprotoLabelDefs::LabelValueDefinition child;
            ComAtprotoLabelDefs::copyLabelValueDefinition(s.toObject(), child);
            dest.labelValueDefinitions.append(child);
        }
    }
}
void copyLabelerViewDetailed(const QJsonObject &src, AppBskyLabelerDefs::LabelerViewDetailed &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        AppBskyActorDefs::copyProfileView(src.value("creator").toObject(), dest.creator);
        AppBskyLabelerDefs::copyLabelerPolicies(src.value("policies").toObject(), dest.policies);
        dest.likeCount = src.value("likeCount").toInt();
        copyLabelerViewerState(src.value("viewer").toObject(), dest.viewer);
        dest.indexedAt = src.value("indexedAt").toString();
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
    }
}
}
// app.bsky.feed.describeFeedGenerator
namespace AppBskyFeedDescribeFeedGenerator {
void copyFeed(const QJsonObject &src, AppBskyFeedDescribeFeedGenerator::Feed &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
    }
}
void copyLinks(const QJsonObject &src, AppBskyFeedDescribeFeedGenerator::Links &dest)
{
    if (!src.isEmpty()) {
        dest.privacyPolicy = src.value("privacyPolicy").toString();
        dest.termsOfService = src.value("termsOfService").toString();
    }
}
}
// app.bsky.feed.generator
namespace AppBskyFeedGenerator {
void copyMain(const QJsonObject &src, AppBskyFeedGenerator::Main &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
        dest.displayName = src.value("displayName").toString();
        dest.description = src.value("description").toString();
        for (const auto &s : src.value("descriptionFacets").toArray()) {
            AppBskyRichtextFacet::Main child;
            AppBskyRichtextFacet::copyMain(s.toObject(), child);
            dest.descriptionFacets.append(child);
        }
        LexiconsTypeUnknown::copyBlob(src.value("avatar").toObject(), dest.avatar);
        dest.acceptsInteractions = src.value("acceptsInteractions").toBool();
        QString labels_type = src.value("labels").toObject().value("$type").toString();
        if (labels_type == QStringLiteral("com.atproto.label.defs#selfLabels")) {
            dest.labels_type =
                    AppBskyFeedGenerator::MainLabelsType::labels_ComAtprotoLabelDefs_SelfLabels;
            ComAtprotoLabelDefs::copySelfLabels(src.value("labels").toObject(),
                                                dest.labels_ComAtprotoLabelDefs_SelfLabels);
        }
        dest.createdAt = src.value("createdAt").toString();
    }
}
}
// app.bsky.feed.getLikes
namespace AppBskyFeedGetLikes {
void copyLike(const QJsonObject &src, AppBskyFeedGetLikes::Like &dest)
{
    if (!src.isEmpty()) {
        dest.indexedAt = src.value("indexedAt").toString();
        dest.createdAt = src.value("createdAt").toString();
        AppBskyActorDefs::copyProfileView(src.value("actor").toObject(), dest.actor);
    }
}
}
// app.bsky.feed.like
namespace AppBskyFeedLike {
void copyMain(const QJsonObject &src, AppBskyFeedLike::Main &dest)
{
    if (!src.isEmpty()) {
        ComAtprotoRepoStrongRef::copyMain(src.value("subject").toObject(), dest.subject);
        dest.createdAt = src.value("createdAt").toString();
    }
}
}
// app.bsky.feed.post
namespace AppBskyFeedPost {
void copyTextSlice(const QJsonObject &src, AppBskyFeedPost::TextSlice &dest)
{
    if (!src.isEmpty()) {
        dest.start = src.value("start").toInt();
        dest.end = src.value("end").toInt();
    }
}
void copyEntity(const QJsonObject &src, AppBskyFeedPost::Entity &dest)
{
    if (!src.isEmpty()) {
        copyTextSlice(src.value("index").toObject(), dest.index);
        dest.type = src.value("type").toString();
        dest.value = src.value("value").toString();
    }
}
void copyReplyRef(const QJsonObject &src, AppBskyFeedPost::ReplyRef &dest)
{
    if (!src.isEmpty()) {
        ComAtprotoRepoStrongRef::copyMain(src.value("root").toObject(), dest.root);
        ComAtprotoRepoStrongRef::copyMain(src.value("parent").toObject(), dest.parent);
    }
}
void copyMain(const QJsonObject &src, AppBskyFeedPost::Main &dest)
{
    if (!src.isEmpty()) {
        dest.text = src.value("text").toString();
        for (const auto &s : src.value("facets").toArray()) {
            AppBskyRichtextFacet::Main child;
            AppBskyRichtextFacet::copyMain(s.toObject(), child);
            dest.facets.append(child);
        }
        copyReplyRef(src.value("reply").toObject(), dest.reply);
        QString embed_type = src.value("embed").toObject().value("$type").toString();
        if (embed_type == QStringLiteral("app.bsky.embed.images")) {
            dest.embed_type = AppBskyFeedPost::MainEmbedType::embed_AppBskyEmbedImages_Main;
            AppBskyEmbedImages::copyMain(src.value("embed").toObject(),
                                         dest.embed_AppBskyEmbedImages_Main);
        }
        if (embed_type == QStringLiteral("app.bsky.embed.external")) {
            dest.embed_type = AppBskyFeedPost::MainEmbedType::embed_AppBskyEmbedExternal_Main;
            AppBskyEmbedExternal::copyMain(src.value("embed").toObject(),
                                           dest.embed_AppBskyEmbedExternal_Main);
        }
        if (embed_type == QStringLiteral("app.bsky.embed.record")) {
            dest.embed_type = AppBskyFeedPost::MainEmbedType::embed_AppBskyEmbedRecord_Main;
            AppBskyEmbedRecord::copyMain(src.value("embed").toObject(),
                                         dest.embed_AppBskyEmbedRecord_Main);
        }
        if (embed_type == QStringLiteral("app.bsky.embed.recordWithMedia")) {
            dest.embed_type =
                    AppBskyFeedPost::MainEmbedType::embed_AppBskyEmbedRecordWithMedia_Main;
            AppBskyEmbedRecordWithMedia::copyMain(src.value("embed").toObject(),
                                                  dest.embed_AppBskyEmbedRecordWithMedia_Main);
        }
        for (const auto &value : src.value("langs").toArray()) {
            dest.langs.append(value.toString());
        }
        QString labels_type = src.value("labels").toObject().value("$type").toString();
        if (labels_type == QStringLiteral("com.atproto.label.defs#selfLabels")) {
            dest.labels_type =
                    AppBskyFeedPost::MainLabelsType::labels_ComAtprotoLabelDefs_SelfLabels;
            ComAtprotoLabelDefs::copySelfLabels(src.value("labels").toObject(),
                                                dest.labels_ComAtprotoLabelDefs_SelfLabels);
        }
        for (const auto &value : src.value("tags").toArray()) {
            dest.tags.append(value.toString());
        }
        dest.createdAt = src.value("createdAt").toString();
        dest.via = src.value("via").toString();
    }
}
}
// app.bsky.feed.repost
namespace AppBskyFeedRepost {
void copyMain(const QJsonObject &src, AppBskyFeedRepost::Main &dest)
{
    if (!src.isEmpty()) {
        ComAtprotoRepoStrongRef::copyMain(src.value("subject").toObject(), dest.subject);
        dest.createdAt = src.value("createdAt").toString();
    }
}
}
// app.bsky.feed.threadgate
namespace AppBskyFeedThreadgate {
void copyMentionRule(const QJsonObject &src, AppBskyFeedThreadgate::MentionRule &dest)
{
    if (!src.isEmpty()) { }
}
void copyFollowingRule(const QJsonObject &src, AppBskyFeedThreadgate::FollowingRule &dest)
{
    if (!src.isEmpty()) { }
}
void copyListRule(const QJsonObject &src, AppBskyFeedThreadgate::ListRule &dest)
{
    if (!src.isEmpty()) {
        dest.list = src.value("list").toString();
    }
}
void copyMain(const QJsonObject &src, AppBskyFeedThreadgate::Main &dest)
{
    if (!src.isEmpty()) {
        dest.post = src.value("post").toString();
        // array<union> allow
        for (const auto &value : src.value("allow").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.feed.threadgate#mentionRule")) {
                AppBskyFeedThreadgate::MentionRule child;
                AppBskyFeedThreadgate::copyMentionRule(value.toObject(), child);
                dest.allow_MentionRule.append(child);
            }
        }
        for (const auto &value : src.value("allow").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.feed.threadgate#followingRule")) {
                AppBskyFeedThreadgate::FollowingRule child;
                AppBskyFeedThreadgate::copyFollowingRule(value.toObject(), child);
                dest.allow_FollowingRule.append(child);
            }
        }
        for (const auto &value : src.value("allow").toArray()) {
            QString value_type = value.toObject().value("$type").toString();
            if (value_type == QStringLiteral("app.bsky.feed.threadgate#listRule")) {
                AppBskyFeedThreadgate::ListRule child;
                AppBskyFeedThreadgate::copyListRule(value.toObject(), child);
                dest.allow_ListRule.append(child);
            }
        }
        dest.createdAt = src.value("createdAt").toString();
    }
}
}
// app.bsky.graph.block
namespace AppBskyGraphBlock {
void copyMain(const QJsonObject &src, AppBskyGraphBlock::Main &dest)
{
    if (!src.isEmpty()) {
        dest.subject = src.value("subject").toString();
        dest.createdAt = src.value("createdAt").toString();
    }
}
}
// app.bsky.graph.follow
namespace AppBskyGraphFollow {
void copyMain(const QJsonObject &src, AppBskyGraphFollow::Main &dest)
{
    if (!src.isEmpty()) {
        dest.subject = src.value("subject").toString();
        dest.createdAt = src.value("createdAt").toString();
    }
}
}
// app.bsky.graph.list
namespace AppBskyGraphList {
void copyMain(const QJsonObject &src, AppBskyGraphList::Main &dest)
{
    if (!src.isEmpty()) {
        AppBskyGraphDefs::copyListPurpose(src.value("purpose"), dest.purpose);
        dest.name = src.value("name").toString();
        dest.description = src.value("description").toString();
        for (const auto &s : src.value("descriptionFacets").toArray()) {
            AppBskyRichtextFacet::Main child;
            AppBskyRichtextFacet::copyMain(s.toObject(), child);
            dest.descriptionFacets.append(child);
        }
        LexiconsTypeUnknown::copyBlob(src.value("avatar").toObject(), dest.avatar);
        QString labels_type = src.value("labels").toObject().value("$type").toString();
        if (labels_type == QStringLiteral("com.atproto.label.defs#selfLabels")) {
            dest.labels_type =
                    AppBskyGraphList::MainLabelsType::labels_ComAtprotoLabelDefs_SelfLabels;
            ComAtprotoLabelDefs::copySelfLabels(src.value("labels").toObject(),
                                                dest.labels_ComAtprotoLabelDefs_SelfLabels);
        }
        dest.createdAt = src.value("createdAt").toString();
    }
}
}
// app.bsky.graph.listblock
namespace AppBskyGraphListblock {
void copyMain(const QJsonObject &src, AppBskyGraphListblock::Main &dest)
{
    if (!src.isEmpty()) {
        dest.subject = src.value("subject").toString();
        dest.createdAt = src.value("createdAt").toString();
    }
}
}
// app.bsky.graph.listitem
namespace AppBskyGraphListitem {
void copyMain(const QJsonObject &src, AppBskyGraphListitem::Main &dest)
{
    if (!src.isEmpty()) {
        dest.subject = src.value("subject").toString();
        dest.list = src.value("list").toString();
        dest.createdAt = src.value("createdAt").toString();
    }
}
}
// app.bsky.labeler.service
namespace AppBskyLabelerService {
void copyMain(const QJsonObject &src, AppBskyLabelerService::Main &dest)
{
    if (!src.isEmpty()) {
        AppBskyLabelerDefs::copyLabelerPolicies(src.value("policies").toObject(), dest.policies);
        QString labels_type = src.value("labels").toObject().value("$type").toString();
        if (labels_type == QStringLiteral("com.atproto.label.defs#selfLabels")) {
            dest.labels_type =
                    AppBskyLabelerService::MainLabelsType::labels_ComAtprotoLabelDefs_SelfLabels;
            ComAtprotoLabelDefs::copySelfLabels(src.value("labels").toObject(),
                                                dest.labels_ComAtprotoLabelDefs_SelfLabels);
        }
        dest.createdAt = src.value("createdAt").toString();
    }
}
}
// app.bsky.notification.listNotifications
namespace AppBskyNotificationListNotifications {
void copyNotification(const QJsonObject &src,
                      AppBskyNotificationListNotifications::Notification &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        AppBskyActorDefs::copyProfileView(src.value("author").toObject(), dest.author);
        dest.reason = src.value("reason").toString();
        dest.reasonSubject = src.value("reasonSubject").toString();
        LexiconsTypeUnknown::copyUnknown(src.value("record").toObject(), dest.record);
        dest.isRead = src.value("isRead").toBool();
        dest.indexedAt = src.value("indexedAt").toString();
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
    }
}
}
// app.bsky.unspecced.defs
namespace AppBskyUnspeccedDefs {
void copySkeletonSearchPost(const QJsonObject &src, AppBskyUnspeccedDefs::SkeletonSearchPost &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
    }
}
void copySkeletonSearchActor(const QJsonObject &src,
                             AppBskyUnspeccedDefs::SkeletonSearchActor &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
    }
}
}
// app.bsky.unspecced.getTaggedSuggestions
namespace AppBskyUnspeccedGetTaggedSuggestions {
void copySuggestion(const QJsonObject &src, AppBskyUnspeccedGetTaggedSuggestions::Suggestion &dest)
{
    if (!src.isEmpty()) {
        dest.tag = src.value("tag").toString();
        dest.subjectType = src.value("subjectType").toString();
        dest.subject = src.value("subject").toString();
    }
}
}
// com.atproto.admin.defs
namespace ComAtprotoAdminDefs {
void copyStatusAttr(const QJsonObject &src, ComAtprotoAdminDefs::StatusAttr &dest)
{
    if (!src.isEmpty()) {
        dest.applied = src.value("applied").toBool();
        dest.ref = src.value("ref").toString();
    }
}
void copyAccountView(const QJsonObject &src, ComAtprotoAdminDefs::AccountView &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
        dest.handle = src.value("handle").toString();
        dest.email = src.value("email").toString();
        dest.indexedAt = src.value("indexedAt").toString();
        ComAtprotoServerDefs::copyInviteCode(src.value("invitedBy").toObject(), dest.invitedBy);
        for (const auto &s : src.value("invites").toArray()) {
            ComAtprotoServerDefs::InviteCode child;
            ComAtprotoServerDefs::copyInviteCode(s.toObject(), child);
            dest.invites.append(child);
        }
        dest.invitesDisabled = src.value("invitesDisabled").toBool();
        dest.emailConfirmedAt = src.value("emailConfirmedAt").toString();
        dest.inviteNote = src.value("inviteNote").toString();
    }
}
void copyRepoRef(const QJsonObject &src, ComAtprotoAdminDefs::RepoRef &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
    }
}
void copyRepoBlobRef(const QJsonObject &src, ComAtprotoAdminDefs::RepoBlobRef &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
        dest.cid = src.value("cid").toString();
        dest.recordUri = src.value("recordUri").toString();
    }
}
}
// com.atproto.server.defs
namespace ComAtprotoServerDefs {
void copyInviteCodeUse(const QJsonObject &src, ComAtprotoServerDefs::InviteCodeUse &dest)
{
    if (!src.isEmpty()) {
        dest.usedBy = src.value("usedBy").toString();
        dest.usedAt = src.value("usedAt").toString();
    }
}
void copyInviteCode(const QJsonObject &src, ComAtprotoServerDefs::InviteCode &dest)
{
    if (!src.isEmpty()) {
        dest.code = src.value("code").toString();
        dest.available = src.value("available").toInt();
        dest.disabled = src.value("disabled").toBool();
        dest.forAccount = src.value("forAccount").toString();
        dest.createdBy = src.value("createdBy").toString();
        dest.createdAt = src.value("createdAt").toString();
        for (const auto &s : src.value("uses").toArray()) {
            InviteCodeUse child;
            copyInviteCodeUse(s.toObject(), child);
            dest.uses.append(child);
        }
    }
}
void copyDidDocVerificationMethod(const QJsonObject &src,
                                  ComAtprotoServerDefs::DidDocVerificationMethod &dest)
{
    if (!src.isEmpty()) {
        dest.id = src.value("id").toString();
        dest.type = src.value("type").toString();
        dest.controller = src.value("controller").toString();
        dest.publicKeyMultibase = src.value("publicKeyMultibase").toString();
    }
}
void copyDidDocService(const QJsonObject &src, ComAtprotoServerDefs::DidDocService &dest)
{
    if (!src.isEmpty()) {
        dest.id = src.value("id").toString();
        dest.type = src.value("type").toString();
        dest.serviceEndpoint = src.value("serviceEndpoint").toString();
    }
}
void copyDidDoc(const QJsonObject &src, ComAtprotoServerDefs::DidDoc &dest)
{
    if (!src.isEmpty()) {
        for (const auto &value : src.value("context").toArray()) {
            dest.context.append(value.toString());
        }
        dest.id = src.value("id").toString();
        dest.alsoKnownAs = src.value("alsoKnownAs").toString();
        for (const auto &s : src.value("verificationMethod").toArray()) {
            DidDocVerificationMethod child;
            copyDidDocVerificationMethod(s.toObject(), child);
            dest.verificationMethod.append(child);
        }
        for (const auto &s : src.value("service").toArray()) {
            DidDocService child;
            copyDidDocService(s.toObject(), child);
            dest.service.append(child);
        }
    }
}
}
// com.atproto.label.subscribeLabels
namespace ComAtprotoLabelSubscribeLabels {
void copyLabels(const QJsonObject &src, ComAtprotoLabelSubscribeLabels::Labels &dest)
{
    if (!src.isEmpty()) {
        dest.seq = src.value("seq").toInt();
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
    }
}
void copyInfo(const QJsonObject &src, ComAtprotoLabelSubscribeLabels::Info &dest)
{
    if (!src.isEmpty()) {
        dest.name = src.value("name").toString();
        dest.message = src.value("message").toString();
    }
}
}
// com.atproto.moderation.defs
namespace ComAtprotoModerationDefs {
void copyReasonType(const QJsonValue &src, ComAtprotoModerationDefs::ReasonType &dest)
{
    dest = src.toString();
}
}
// com.atproto.repo.applyWrites
namespace ComAtprotoRepoApplyWrites {
void copyCreate(const QJsonObject &src, ComAtprotoRepoApplyWrites::Create &dest)
{
    if (!src.isEmpty()) {
        dest.collection = src.value("collection").toString();
        dest.rkey = src.value("rkey").toString();
        LexiconsTypeUnknown::copyUnknown(src.value("value").toObject(), dest.value);
    }
}
void copyUpdate(const QJsonObject &src, ComAtprotoRepoApplyWrites::Update &dest)
{
    if (!src.isEmpty()) {
        dest.collection = src.value("collection").toString();
        dest.rkey = src.value("rkey").toString();
        LexiconsTypeUnknown::copyUnknown(src.value("value").toObject(), dest.value);
    }
}
void copyDelete(const QJsonObject &src, ComAtprotoRepoApplyWrites::Delete &dest)
{
    if (!src.isEmpty()) {
        dest.collection = src.value("collection").toString();
        dest.rkey = src.value("rkey").toString();
    }
}
}
// com.atproto.repo.listMissingBlobs
namespace ComAtprotoRepoListMissingBlobs {
void copyRecordBlob(const QJsonObject &src, ComAtprotoRepoListMissingBlobs::RecordBlob &dest)
{
    if (!src.isEmpty()) {
        dest.cid = src.value("cid").toString();
        dest.recordUri = src.value("recordUri").toString();
    }
}
}
// com.atproto.repo.listRecords
namespace ComAtprotoRepoListRecords {
void copyRecord(const QJsonObject &src, ComAtprotoRepoListRecords::Record &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        LexiconsTypeUnknown::copyUnknown(src.value("value").toObject(), dest.value);
    }
}
}
// com.atproto.server.createAppPassword
namespace ComAtprotoServerCreateAppPassword {
void copyAppPassword(const QJsonObject &src, ComAtprotoServerCreateAppPassword::AppPassword &dest)
{
    if (!src.isEmpty()) {
        dest.name = src.value("name").toString();
        dest.password = src.value("password").toString();
        dest.createdAt = src.value("createdAt").toString();
    }
}
}
// com.atproto.server.createInviteCodes
namespace ComAtprotoServerCreateInviteCodes {
void copyAccountCodes(const QJsonObject &src, ComAtprotoServerCreateInviteCodes::AccountCodes &dest)
{
    if (!src.isEmpty()) {
        dest.account = src.value("account").toString();
        for (const auto &value : src.value("codes").toArray()) {
            dest.codes.append(value.toString());
        }
    }
}
}
// com.atproto.server.describeServer
namespace ComAtprotoServerDescribeServer {
void copyLinks(const QJsonObject &src, ComAtprotoServerDescribeServer::Links &dest)
{
    if (!src.isEmpty()) {
        dest.privacyPolicy = src.value("privacyPolicy").toString();
        dest.termsOfService = src.value("termsOfService").toString();
    }
}
void copyContact(const QJsonObject &src, ComAtprotoServerDescribeServer::Contact &dest)
{
    if (!src.isEmpty()) {
        dest.email = src.value("email").toString();
    }
}
}
// com.atproto.server.listAppPasswords
namespace ComAtprotoServerListAppPasswords {
void copyAppPassword(const QJsonObject &src, ComAtprotoServerListAppPasswords::AppPassword &dest)
{
    if (!src.isEmpty()) {
        dest.name = src.value("name").toString();
        dest.createdAt = src.value("createdAt").toString();
    }
}
}
// com.atproto.sync.listRepos
namespace ComAtprotoSyncListRepos {
void copyRepo(const QJsonObject &src, ComAtprotoSyncListRepos::Repo &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
        dest.head = src.value("head").toString();
        dest.rev = src.value("rev").toString();
    }
}
}
// com.atproto.sync.subscribeRepos
namespace ComAtprotoSyncSubscribeRepos {
void copyRepoOp(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::RepoOp &dest)
{
    if (!src.isEmpty()) {
        dest.action = src.value("action").toString();
        dest.path = src.value("path").toString();
    }
}
void copyCommit(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::Commit &dest)
{
    if (!src.isEmpty()) {
        dest.seq = src.value("seq").toInt();
        dest.tooBig = src.value("tooBig").toBool();
        dest.repo = src.value("repo").toString();
        dest.rev = src.value("rev").toString();
        dest.since = src.value("since").toString();
        for (const auto &s : src.value("ops").toArray()) {
            RepoOp child;
            copyRepoOp(s.toObject(), child);
            dest.ops.append(child);
        }
        dest.time = src.value("time").toString();
    }
}
void copyIdentity(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::Identity &dest)
{
    if (!src.isEmpty()) {
        dest.seq = src.value("seq").toInt();
        dest.did = src.value("did").toString();
        dest.time = src.value("time").toString();
    }
}
void copyHandle(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::Handle &dest)
{
    if (!src.isEmpty()) {
        dest.seq = src.value("seq").toInt();
        dest.did = src.value("did").toString();
        dest.handle = src.value("handle").toString();
        dest.time = src.value("time").toString();
    }
}
void copyMigrate(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::Migrate &dest)
{
    if (!src.isEmpty()) {
        dest.seq = src.value("seq").toInt();
        dest.did = src.value("did").toString();
        dest.migrateTo = src.value("migrateTo").toString();
        dest.time = src.value("time").toString();
    }
}
void copyTombstone(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::Tombstone &dest)
{
    if (!src.isEmpty()) {
        dest.seq = src.value("seq").toInt();
        dest.did = src.value("did").toString();
        dest.time = src.value("time").toString();
    }
}
void copyInfo(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::Info &dest)
{
    if (!src.isEmpty()) {
        dest.name = src.value("name").toString();
        dest.message = src.value("message").toString();
    }
}
}
// tools.ozone.communication.defs
namespace ToolsOzoneCommunicationDefs {
void copyTemplateView(const QJsonObject &src, ToolsOzoneCommunicationDefs::TemplateView &dest)
{
    if (!src.isEmpty()) {
        dest.id = src.value("id").toString();
        dest.name = src.value("name").toString();
        dest.subject = src.value("subject").toString();
        dest.contentMarkdown = src.value("contentMarkdown").toString();
        dest.disabled = src.value("disabled").toBool();
        dest.lastUpdatedBy = src.value("lastUpdatedBy").toString();
        dest.createdAt = src.value("createdAt").toString();
        dest.updatedAt = src.value("updatedAt").toString();
    }
}
}
// tools.ozone.moderation.defs
namespace ToolsOzoneModerationDefs {
void copyModEventTakedown(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventTakedown &dest)
{
    if (!src.isEmpty()) {
        dest.comment = src.value("comment").toString();
        dest.durationInHours = src.value("durationInHours").toInt();
    }
}
void copyModEventReverseTakedown(const QJsonObject &src,
                                 ToolsOzoneModerationDefs::ModEventReverseTakedown &dest)
{
    if (!src.isEmpty()) {
        dest.comment = src.value("comment").toString();
    }
}
void copyModEventComment(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventComment &dest)
{
    if (!src.isEmpty()) {
        dest.comment = src.value("comment").toString();
        dest.sticky = src.value("sticky").toBool();
    }
}
void copyModEventReport(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventReport &dest)
{
    if (!src.isEmpty()) {
        dest.comment = src.value("comment").toString();
        ComAtprotoModerationDefs::copyReasonType(src.value("reportType"), dest.reportType);
    }
}
void copyModEventLabel(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventLabel &dest)
{
    if (!src.isEmpty()) {
        dest.comment = src.value("comment").toString();
        for (const auto &value : src.value("createLabelVals").toArray()) {
            dest.createLabelVals.append(value.toString());
        }
        for (const auto &value : src.value("negateLabelVals").toArray()) {
            dest.negateLabelVals.append(value.toString());
        }
    }
}
void copyModEventAcknowledge(const QJsonObject &src,
                             ToolsOzoneModerationDefs::ModEventAcknowledge &dest)
{
    if (!src.isEmpty()) {
        dest.comment = src.value("comment").toString();
    }
}
void copyModEventEscalate(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventEscalate &dest)
{
    if (!src.isEmpty()) {
        dest.comment = src.value("comment").toString();
    }
}
void copyModEventMute(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventMute &dest)
{
    if (!src.isEmpty()) {
        dest.comment = src.value("comment").toString();
        dest.durationInHours = src.value("durationInHours").toInt();
    }
}
void copyModEventEmail(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventEmail &dest)
{
    if (!src.isEmpty()) {
        dest.subjectLine = src.value("subjectLine").toString();
        dest.content = src.value("content").toString();
        dest.comment = src.value("comment").toString();
    }
}
void copyModEventResolveAppeal(const QJsonObject &src,
                               ToolsOzoneModerationDefs::ModEventResolveAppeal &dest)
{
    if (!src.isEmpty()) {
        dest.comment = src.value("comment").toString();
    }
}
void copyModEventDivert(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventDivert &dest)
{
    if (!src.isEmpty()) {
        dest.comment = src.value("comment").toString();
    }
}
void copyModEventView(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventView &dest)
{
    if (!src.isEmpty()) {
        dest.id = src.value("id").toInt();
        QString event_type = src.value("event").toObject().value("$type").toString();
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventTakedown")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewEventType::event_ModEventTakedown;
            ToolsOzoneModerationDefs::copyModEventTakedown(src.value("event").toObject(),
                                                           dest.event_ModEventTakedown);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventReverseTakedown")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewEventType::event_ModEventReverseTakedown;
            ToolsOzoneModerationDefs::copyModEventReverseTakedown(
                    src.value("event").toObject(), dest.event_ModEventReverseTakedown);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventComment")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewEventType::event_ModEventComment;
            ToolsOzoneModerationDefs::copyModEventComment(src.value("event").toObject(),
                                                          dest.event_ModEventComment);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventReport")) {
            dest.event_type = ToolsOzoneModerationDefs::ModEventViewEventType::event_ModEventReport;
            ToolsOzoneModerationDefs::copyModEventReport(src.value("event").toObject(),
                                                         dest.event_ModEventReport);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventLabel")) {
            dest.event_type = ToolsOzoneModerationDefs::ModEventViewEventType::event_ModEventLabel;
            ToolsOzoneModerationDefs::copyModEventLabel(src.value("event").toObject(),
                                                        dest.event_ModEventLabel);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventAcknowledge")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewEventType::event_ModEventAcknowledge;
            ToolsOzoneModerationDefs::copyModEventAcknowledge(src.value("event").toObject(),
                                                              dest.event_ModEventAcknowledge);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventEscalate")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewEventType::event_ModEventEscalate;
            ToolsOzoneModerationDefs::copyModEventEscalate(src.value("event").toObject(),
                                                           dest.event_ModEventEscalate);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventMute")) {
            dest.event_type = ToolsOzoneModerationDefs::ModEventViewEventType::event_ModEventMute;
            ToolsOzoneModerationDefs::copyModEventMute(src.value("event").toObject(),
                                                       dest.event_ModEventMute);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventEmail")) {
            dest.event_type = ToolsOzoneModerationDefs::ModEventViewEventType::event_ModEventEmail;
            ToolsOzoneModerationDefs::copyModEventEmail(src.value("event").toObject(),
                                                        dest.event_ModEventEmail);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventResolveAppeal")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewEventType::event_ModEventResolveAppeal;
            ToolsOzoneModerationDefs::copyModEventResolveAppeal(src.value("event").toObject(),
                                                                dest.event_ModEventResolveAppeal);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventDivert")) {
            dest.event_type = ToolsOzoneModerationDefs::ModEventViewEventType::event_ModEventDivert;
            ToolsOzoneModerationDefs::copyModEventDivert(src.value("event").toObject(),
                                                         dest.event_ModEventDivert);
        }
        QString subject_type = src.value("subject").toObject().value("$type").toString();
        if (subject_type == QStringLiteral("com.atproto.admin.defs#repoRef")) {
            dest.subject_type = ToolsOzoneModerationDefs::ModEventViewSubjectType::
                    subject_ComAtprotoAdminDefs_RepoRef;
            ComAtprotoAdminDefs::copyRepoRef(src.value("subject").toObject(),
                                             dest.subject_ComAtprotoAdminDefs_RepoRef);
        }
        if (subject_type == QStringLiteral("com.atproto.repo.strongRef")) {
            dest.subject_type = ToolsOzoneModerationDefs::ModEventViewSubjectType::
                    subject_ComAtprotoRepoStrongRef_Main;
            ComAtprotoRepoStrongRef::copyMain(src.value("subject").toObject(),
                                              dest.subject_ComAtprotoRepoStrongRef_Main);
        }
        for (const auto &value : src.value("subjectBlobCids").toArray()) {
            dest.subjectBlobCids.append(value.toString());
        }
        dest.createdBy = src.value("createdBy").toString();
        dest.createdAt = src.value("createdAt").toString();
        dest.creatorHandle = src.value("creatorHandle").toString();
        dest.subjectHandle = src.value("subjectHandle").toString();
    }
}
void copySubjectReviewState(const QJsonValue &src,
                            ToolsOzoneModerationDefs::SubjectReviewState &dest)
{
    dest = src.toString();
}
void copySubjectStatusView(const QJsonObject &src,
                           ToolsOzoneModerationDefs::SubjectStatusView &dest)
{
    if (!src.isEmpty()) {
        dest.id = src.value("id").toInt();
        QString subject_type = src.value("subject").toObject().value("$type").toString();
        if (subject_type == QStringLiteral("com.atproto.admin.defs#repoRef")) {
            dest.subject_type = ToolsOzoneModerationDefs::SubjectStatusViewSubjectType::
                    subject_ComAtprotoAdminDefs_RepoRef;
            ComAtprotoAdminDefs::copyRepoRef(src.value("subject").toObject(),
                                             dest.subject_ComAtprotoAdminDefs_RepoRef);
        }
        if (subject_type == QStringLiteral("com.atproto.repo.strongRef")) {
            dest.subject_type = ToolsOzoneModerationDefs::SubjectStatusViewSubjectType::
                    subject_ComAtprotoRepoStrongRef_Main;
            ComAtprotoRepoStrongRef::copyMain(src.value("subject").toObject(),
                                              dest.subject_ComAtprotoRepoStrongRef_Main);
        }
        for (const auto &value : src.value("subjectBlobCids").toArray()) {
            dest.subjectBlobCids.append(value.toString());
        }
        dest.subjectRepoHandle = src.value("subjectRepoHandle").toString();
        dest.updatedAt = src.value("updatedAt").toString();
        dest.createdAt = src.value("createdAt").toString();
        copySubjectReviewState(src.value("reviewState"), dest.reviewState);
        dest.comment = src.value("comment").toString();
        dest.muteUntil = src.value("muteUntil").toString();
        dest.lastReviewedBy = src.value("lastReviewedBy").toString();
        dest.lastReviewedAt = src.value("lastReviewedAt").toString();
        dest.lastReportedAt = src.value("lastReportedAt").toString();
        dest.lastAppealedAt = src.value("lastAppealedAt").toString();
        dest.takendown = src.value("takendown").toBool();
        dest.appealed = src.value("appealed").toBool();
        dest.suspendUntil = src.value("suspendUntil").toString();
        for (const auto &value : src.value("tags").toArray()) {
            dest.tags.append(value.toString());
        }
    }
}
void copyModeration(const QJsonObject &src, ToolsOzoneModerationDefs::Moderation &dest)
{
    if (!src.isEmpty()) {
        copySubjectStatusView(src.value("subjectStatus").toObject(), dest.subjectStatus);
    }
}
void copyRepoView(const QJsonObject &src, ToolsOzoneModerationDefs::RepoView &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
        dest.handle = src.value("handle").toString();
        dest.email = src.value("email").toString();
        dest.indexedAt = src.value("indexedAt").toString();
        copyModeration(src.value("moderation").toObject(), dest.moderation);
        ComAtprotoServerDefs::copyInviteCode(src.value("invitedBy").toObject(), dest.invitedBy);
        dest.invitesDisabled = src.value("invitesDisabled").toBool();
        dest.inviteNote = src.value("inviteNote").toString();
    }
}
void copyRepoViewNotFound(const QJsonObject &src, ToolsOzoneModerationDefs::RepoViewNotFound &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
    }
}
void copyRecordView(const QJsonObject &src, ToolsOzoneModerationDefs::RecordView &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        LexiconsTypeUnknown::copyUnknown(src.value("value").toObject(), dest.value);
        for (const auto &value : src.value("blobCids").toArray()) {
            dest.blobCids.append(value.toString());
        }
        dest.indexedAt = src.value("indexedAt").toString();
        copyModeration(src.value("moderation").toObject(), dest.moderation);
        copyRepoView(src.value("repo").toObject(), dest.repo);
    }
}
void copyRecordViewNotFound(const QJsonObject &src,
                            ToolsOzoneModerationDefs::RecordViewNotFound &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
    }
}
void copyImageDetails(const QJsonObject &src, ToolsOzoneModerationDefs::ImageDetails &dest)
{
    if (!src.isEmpty()) {
        dest.width = src.value("width").toInt();
        dest.height = src.value("height").toInt();
    }
}
void copyVideoDetails(const QJsonObject &src, ToolsOzoneModerationDefs::VideoDetails &dest)
{
    if (!src.isEmpty()) {
        dest.width = src.value("width").toInt();
        dest.height = src.value("height").toInt();
        dest.length = src.value("length").toInt();
    }
}
void copyBlobView(const QJsonObject &src, ToolsOzoneModerationDefs::BlobView &dest)
{
    if (!src.isEmpty()) {
        dest.cid = src.value("cid").toString();
        dest.mimeType = src.value("mimeType").toString();
        dest.size = src.value("size").toInt();
        dest.createdAt = src.value("createdAt").toString();
        QString details_type = src.value("details").toObject().value("$type").toString();
        if (details_type == QStringLiteral("tools.ozone.moderation.defs#imageDetails")) {
            dest.details_type = ToolsOzoneModerationDefs::BlobViewDetailsType::details_ImageDetails;
            ToolsOzoneModerationDefs::copyImageDetails(src.value("details").toObject(),
                                                       dest.details_ImageDetails);
        }
        if (details_type == QStringLiteral("tools.ozone.moderation.defs#videoDetails")) {
            dest.details_type = ToolsOzoneModerationDefs::BlobViewDetailsType::details_VideoDetails;
            ToolsOzoneModerationDefs::copyVideoDetails(src.value("details").toObject(),
                                                       dest.details_VideoDetails);
        }
        copyModeration(src.value("moderation").toObject(), dest.moderation);
    }
}
void copyModEventViewDetail(const QJsonObject &src,
                            ToolsOzoneModerationDefs::ModEventViewDetail &dest)
{
    if (!src.isEmpty()) {
        dest.id = src.value("id").toInt();
        QString event_type = src.value("event").toObject().value("$type").toString();
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventTakedown")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewDetailEventType::event_ModEventTakedown;
            ToolsOzoneModerationDefs::copyModEventTakedown(src.value("event").toObject(),
                                                           dest.event_ModEventTakedown);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventReverseTakedown")) {
            dest.event_type = ToolsOzoneModerationDefs::ModEventViewDetailEventType::
                    event_ModEventReverseTakedown;
            ToolsOzoneModerationDefs::copyModEventReverseTakedown(
                    src.value("event").toObject(), dest.event_ModEventReverseTakedown);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventComment")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewDetailEventType::event_ModEventComment;
            ToolsOzoneModerationDefs::copyModEventComment(src.value("event").toObject(),
                                                          dest.event_ModEventComment);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventReport")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewDetailEventType::event_ModEventReport;
            ToolsOzoneModerationDefs::copyModEventReport(src.value("event").toObject(),
                                                         dest.event_ModEventReport);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventLabel")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewDetailEventType::event_ModEventLabel;
            ToolsOzoneModerationDefs::copyModEventLabel(src.value("event").toObject(),
                                                        dest.event_ModEventLabel);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventAcknowledge")) {
            dest.event_type = ToolsOzoneModerationDefs::ModEventViewDetailEventType::
                    event_ModEventAcknowledge;
            ToolsOzoneModerationDefs::copyModEventAcknowledge(src.value("event").toObject(),
                                                              dest.event_ModEventAcknowledge);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventEscalate")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewDetailEventType::event_ModEventEscalate;
            ToolsOzoneModerationDefs::copyModEventEscalate(src.value("event").toObject(),
                                                           dest.event_ModEventEscalate);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventMute")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewDetailEventType::event_ModEventMute;
            ToolsOzoneModerationDefs::copyModEventMute(src.value("event").toObject(),
                                                       dest.event_ModEventMute);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventEmail")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewDetailEventType::event_ModEventEmail;
            ToolsOzoneModerationDefs::copyModEventEmail(src.value("event").toObject(),
                                                        dest.event_ModEventEmail);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventResolveAppeal")) {
            dest.event_type = ToolsOzoneModerationDefs::ModEventViewDetailEventType::
                    event_ModEventResolveAppeal;
            ToolsOzoneModerationDefs::copyModEventResolveAppeal(src.value("event").toObject(),
                                                                dest.event_ModEventResolveAppeal);
        }
        if (event_type == QStringLiteral("tools.ozone.moderation.defs#modEventDivert")) {
            dest.event_type =
                    ToolsOzoneModerationDefs::ModEventViewDetailEventType::event_ModEventDivert;
            ToolsOzoneModerationDefs::copyModEventDivert(src.value("event").toObject(),
                                                         dest.event_ModEventDivert);
        }
        QString subject_type = src.value("subject").toObject().value("$type").toString();
        if (subject_type == QStringLiteral("tools.ozone.moderation.defs#repoView")) {
            dest.subject_type =
                    ToolsOzoneModerationDefs::ModEventViewDetailSubjectType::subject_RepoView;
            ToolsOzoneModerationDefs::copyRepoView(src.value("subject").toObject(),
                                                   dest.subject_RepoView);
        }
        if (subject_type == QStringLiteral("tools.ozone.moderation.defs#repoViewNotFound")) {
            dest.subject_type = ToolsOzoneModerationDefs::ModEventViewDetailSubjectType::
                    subject_RepoViewNotFound;
            ToolsOzoneModerationDefs::copyRepoViewNotFound(src.value("subject").toObject(),
                                                           dest.subject_RepoViewNotFound);
        }
        if (subject_type == QStringLiteral("tools.ozone.moderation.defs#recordView")) {
            dest.subject_type =
                    ToolsOzoneModerationDefs::ModEventViewDetailSubjectType::subject_RecordView;
            ToolsOzoneModerationDefs::copyRecordView(src.value("subject").toObject(),
                                                     dest.subject_RecordView);
        }
        if (subject_type == QStringLiteral("tools.ozone.moderation.defs#recordViewNotFound")) {
            dest.subject_type = ToolsOzoneModerationDefs::ModEventViewDetailSubjectType::
                    subject_RecordViewNotFound;
            ToolsOzoneModerationDefs::copyRecordViewNotFound(src.value("subject").toObject(),
                                                             dest.subject_RecordViewNotFound);
        }
        for (const auto &s : src.value("subjectBlobs").toArray()) {
            BlobView child;
            copyBlobView(s.toObject(), child);
            dest.subjectBlobs.append(child);
        }
        dest.createdBy = src.value("createdBy").toString();
        dest.createdAt = src.value("createdAt").toString();
    }
}
void copyModEventUnmute(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventUnmute &dest)
{
    if (!src.isEmpty()) {
        dest.comment = src.value("comment").toString();
    }
}
void copyModEventTag(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventTag &dest)
{
    if (!src.isEmpty()) {
        for (const auto &value : src.value("add").toArray()) {
            dest.add.append(value.toString());
        }
        for (const auto &value : src.value("remove").toArray()) {
            dest.remove.append(value.toString());
        }
        dest.comment = src.value("comment").toString();
    }
}
void copyModerationDetail(const QJsonObject &src, ToolsOzoneModerationDefs::ModerationDetail &dest)
{
    if (!src.isEmpty()) {
        copySubjectStatusView(src.value("subjectStatus").toObject(), dest.subjectStatus);
    }
}
void copyRepoViewDetail(const QJsonObject &src, ToolsOzoneModerationDefs::RepoViewDetail &dest)
{
    if (!src.isEmpty()) {
        dest.did = src.value("did").toString();
        dest.handle = src.value("handle").toString();
        dest.email = src.value("email").toString();
        dest.indexedAt = src.value("indexedAt").toString();
        copyModerationDetail(src.value("moderation").toObject(), dest.moderation);
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
        ComAtprotoServerDefs::copyInviteCode(src.value("invitedBy").toObject(), dest.invitedBy);
        for (const auto &s : src.value("invites").toArray()) {
            ComAtprotoServerDefs::InviteCode child;
            ComAtprotoServerDefs::copyInviteCode(s.toObject(), child);
            dest.invites.append(child);
        }
        dest.invitesDisabled = src.value("invitesDisabled").toBool();
        dest.inviteNote = src.value("inviteNote").toString();
        dest.emailConfirmedAt = src.value("emailConfirmedAt").toString();
    }
}
void copyRecordViewDetail(const QJsonObject &src, ToolsOzoneModerationDefs::RecordViewDetail &dest)
{
    if (!src.isEmpty()) {
        dest.uri = src.value("uri").toString();
        dest.cid = src.value("cid").toString();
        LexiconsTypeUnknown::copyUnknown(src.value("value").toObject(), dest.value);
        for (const auto &s : src.value("blobs").toArray()) {
            BlobView child;
            copyBlobView(s.toObject(), child);
            dest.blobs.append(child);
        }
        for (const auto &s : src.value("labels").toArray()) {
            ComAtprotoLabelDefs::Label child;
            ComAtprotoLabelDefs::copyLabel(s.toObject(), child);
            dest.labels.append(child);
        }
        dest.indexedAt = src.value("indexedAt").toString();
        copyModerationDetail(src.value("moderation").toObject(), dest.moderation);
        copyRepoView(src.value("repo").toObject(), dest.repo);
    }
}
}

}

#endif // LEXICONS_FUNC_CPP
