// This file is generated by "defs2struct.py".
// Please do not edit.

#ifndef LEXICONS_FUNC_H
#define LEXICONS_FUNC_H

#include "lexicons.h"

#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QList>
#include <QString>
#include <QVariant>

namespace AtProtocolType {
// app.bsky.actor.defs
namespace AppBskyActorDefs {
void copyProfileAssociatedChat(const QJsonObject &src,
                               AppBskyActorDefs::ProfileAssociatedChat &dest);
void copyProfileAssociatedActivitySubscription(
        const QJsonObject &src, AppBskyActorDefs::ProfileAssociatedActivitySubscription &dest);
void copyProfileAssociatedGerm(const QJsonObject &src,
                               AppBskyActorDefs::ProfileAssociatedGerm &dest);
void copyProfileAssociated(const QJsonObject &src, AppBskyActorDefs::ProfileAssociated &dest);
void copyKnownFollowers(const QJsonObject &src, AppBskyActorDefs::KnownFollowers &dest);
void copyViewerState(const QJsonObject &src, AppBskyActorDefs::ViewerState &dest);
void copyVerificationView(const QJsonObject &src, AppBskyActorDefs::VerificationView &dest);
void copyVerificationState(const QJsonObject &src, AppBskyActorDefs::VerificationState &dest);
void copyStatusView(const QJsonObject &src, AppBskyActorDefs::StatusView &dest);
void copyProfileViewBasic(const QJsonObject &src, AppBskyActorDefs::ProfileViewBasic &dest);
void copyProfileView(const QJsonObject &src, AppBskyActorDefs::ProfileView &dest);
void copyProfileViewDetailed(const QJsonObject &src, AppBskyActorDefs::ProfileViewDetailed &dest);
void copyAdultContentPref(const QJsonObject &src, AppBskyActorDefs::AdultContentPref &dest);
void copyContentLabelPref(const QJsonObject &src, AppBskyActorDefs::ContentLabelPref &dest);
void copySavedFeedsPref(const QJsonObject &src, AppBskyActorDefs::SavedFeedsPref &dest);
void copySavedFeed(const QJsonObject &src, AppBskyActorDefs::SavedFeed &dest);
void copySavedFeedsPrefV2(const QJsonObject &src, AppBskyActorDefs::SavedFeedsPrefV2 &dest);
void copyPersonalDetailsPref(const QJsonObject &src, AppBskyActorDefs::PersonalDetailsPref &dest);
void copyDeclaredAgePref(const QJsonObject &src, AppBskyActorDefs::DeclaredAgePref &dest);
void copyFeedViewPref(const QJsonObject &src, AppBskyActorDefs::FeedViewPref &dest);
void copyThreadViewPref(const QJsonObject &src, AppBskyActorDefs::ThreadViewPref &dest);
void copyInterestsPref(const QJsonObject &src, AppBskyActorDefs::InterestsPref &dest);
void copyMutedWordTarget(const QJsonValue &src, AppBskyActorDefs::MutedWordTarget &dest);
void copyMutedWord(const QJsonObject &src, AppBskyActorDefs::MutedWord &dest);
void copyMutedWordsPref(const QJsonObject &src, AppBskyActorDefs::MutedWordsPref &dest);
void copyHiddenPostsPref(const QJsonObject &src, AppBskyActorDefs::HiddenPostsPref &dest);
void copyBskyAppProgressGuide(const QJsonObject &src, AppBskyActorDefs::BskyAppProgressGuide &dest);
void copyNux(const QJsonObject &src, AppBskyActorDefs::Nux &dest);
void copyBskyAppStatePref(const QJsonObject &src, AppBskyActorDefs::BskyAppStatePref &dest);
void copyLabelerPrefItem(const QJsonObject &src, AppBskyActorDefs::LabelerPrefItem &dest);
void copyLabelersPref(const QJsonObject &src, AppBskyActorDefs::LabelersPref &dest);
void copyPostInteractionSettingsPref(const QJsonObject &src,
                                     AppBskyActorDefs::PostInteractionSettingsPref &dest);
void copyVerificationPrefs(const QJsonObject &src, AppBskyActorDefs::VerificationPrefs &dest);
void copyLiveEventPreferences(const QJsonObject &src, AppBskyActorDefs::LiveEventPreferences &dest);
void copyPreferences(const QJsonArray &src, AppBskyActorDefs::Preferences &dest);
}
// app.bsky.graph.defs
namespace AppBskyGraphDefs {
void copyListPurpose(const QJsonValue &src, AppBskyGraphDefs::ListPurpose &dest);
void copyListViewerState(const QJsonObject &src, AppBskyGraphDefs::ListViewerState &dest);
void copyListViewBasic(const QJsonObject &src, AppBskyGraphDefs::ListViewBasic &dest);
void copyStarterPackViewBasic(const QJsonObject &src, AppBskyGraphDefs::StarterPackViewBasic &dest);
void copyListView(const QJsonObject &src, AppBskyGraphDefs::ListView &dest);
void copyListItemView(const QJsonObject &src, AppBskyGraphDefs::ListItemView &dest);
void copyStarterPackView(const QJsonObject &src, AppBskyGraphDefs::StarterPackView &dest);
void copyNotFoundActor(const QJsonObject &src, AppBskyGraphDefs::NotFoundActor &dest);
void copyRelationship(const QJsonObject &src, AppBskyGraphDefs::Relationship &dest);
}
// com.atproto.label.defs
namespace ComAtprotoLabelDefs {
void copyLabel(const QJsonObject &src, ComAtprotoLabelDefs::Label &dest);
void copySelfLabel(const QJsonObject &src, ComAtprotoLabelDefs::SelfLabel &dest);
void copySelfLabels(const QJsonObject &src, ComAtprotoLabelDefs::SelfLabels &dest);
void copyLabelValue(const QJsonValue &src, ComAtprotoLabelDefs::LabelValue &dest);
void copyLabelValueDefinitionStrings(const QJsonObject &src,
                                     ComAtprotoLabelDefs::LabelValueDefinitionStrings &dest);
void copyLabelValueDefinition(const QJsonObject &src,
                              ComAtprotoLabelDefs::LabelValueDefinition &dest);
}
// app.bsky.notification.defs
namespace AppBskyNotificationDefs {
void copyActivitySubscription(const QJsonObject &src,
                              AppBskyNotificationDefs::ActivitySubscription &dest);
void copyRecordDeleted(const QJsonObject &src, AppBskyNotificationDefs::RecordDeleted &dest);
void copyChatPreference(const QJsonObject &src, AppBskyNotificationDefs::ChatPreference &dest);
void copyFilterablePreference(const QJsonObject &src,
                              AppBskyNotificationDefs::FilterablePreference &dest);
void copyPreference(const QJsonObject &src, AppBskyNotificationDefs::Preference &dest);
void copyPreferences(const QJsonObject &src, AppBskyNotificationDefs::Preferences &dest);
void copySubjectActivitySubscription(const QJsonObject &src,
                                     AppBskyNotificationDefs::SubjectActivitySubscription &dest);
}
// app.bsky.embed.external
namespace AppBskyEmbedExternal {
void copyColorRGB(const QJsonObject &src, AppBskyEmbedExternal::ColorRGB &dest);
void copyViewExternalSourceTheme(const QJsonObject &src,
                                 AppBskyEmbedExternal::ViewExternalSourceTheme &dest);
void copyViewExternalSource(const QJsonObject &src, AppBskyEmbedExternal::ViewExternalSource &dest);
void copyViewExternal(const QJsonObject &src, AppBskyEmbedExternal::ViewExternal &dest);
void copyView(const QJsonObject &src, AppBskyEmbedExternal::View &dest);
void copyExternal(const QJsonObject &src, AppBskyEmbedExternal::External &dest);
void copyMain(const QJsonObject &src, AppBskyEmbedExternal::Main &dest);
}
// com.atproto.repo.strongRef
namespace ComAtprotoRepoStrongRef {
void copyMain(const QJsonObject &src, ComAtprotoRepoStrongRef::Main &dest);
}
// app.bsky.feed.threadgate
namespace AppBskyFeedThreadgate {
void copyMentionRule(const QJsonObject &src, AppBskyFeedThreadgate::MentionRule &dest);
void copyFollowerRule(const QJsonObject &src, AppBskyFeedThreadgate::FollowerRule &dest);
void copyFollowingRule(const QJsonObject &src, AppBskyFeedThreadgate::FollowingRule &dest);
void copyListRule(const QJsonObject &src, AppBskyFeedThreadgate::ListRule &dest);
void copyMain(const QJsonObject &src, AppBskyFeedThreadgate::Main &dest);
}
// app.bsky.feed.postgate
namespace AppBskyFeedPostgate {
void copyDisableRule(const QJsonObject &src, AppBskyFeedPostgate::DisableRule &dest);
void copyMain(const QJsonObject &src, AppBskyFeedPostgate::Main &dest);
}
// app.bsky.actor.profile
namespace AppBskyActorProfile {
void copyMain(const QJsonObject &src, AppBskyActorProfile::Main &dest);
}
// app.bsky.actor.status
namespace AppBskyActorStatus {
void copyMain(const QJsonObject &src, AppBskyActorStatus::Main &dest);
}
// app.bsky.ageassurance.defs
namespace AppBskyAgeassuranceDefs {
void copyAccess(const QJsonValue &src, AppBskyAgeassuranceDefs::Access &dest);
void copyStatus(const QJsonValue &src, AppBskyAgeassuranceDefs::Status &dest);
void copyState(const QJsonObject &src, AppBskyAgeassuranceDefs::State &dest);
void copyStateMetadata(const QJsonObject &src, AppBskyAgeassuranceDefs::StateMetadata &dest);
void copyConfigRegionRuleDefault(const QJsonObject &src,
                                 AppBskyAgeassuranceDefs::ConfigRegionRuleDefault &dest);
void copyConfigRegionRuleIfDeclaredOverAge(
        const QJsonObject &src, AppBskyAgeassuranceDefs::ConfigRegionRuleIfDeclaredOverAge &dest);
void copyConfigRegionRuleIfDeclaredUnderAge(
        const QJsonObject &src, AppBskyAgeassuranceDefs::ConfigRegionRuleIfDeclaredUnderAge &dest);
void copyConfigRegionRuleIfAssuredOverAge(
        const QJsonObject &src, AppBskyAgeassuranceDefs::ConfigRegionRuleIfAssuredOverAge &dest);
void copyConfigRegionRuleIfAssuredUnderAge(
        const QJsonObject &src, AppBskyAgeassuranceDefs::ConfigRegionRuleIfAssuredUnderAge &dest);
void copyConfigRegionRuleIfAccountNewerThan(
        const QJsonObject &src, AppBskyAgeassuranceDefs::ConfigRegionRuleIfAccountNewerThan &dest);
void copyConfigRegionRuleIfAccountOlderThan(
        const QJsonObject &src, AppBskyAgeassuranceDefs::ConfigRegionRuleIfAccountOlderThan &dest);
void copyConfigRegion(const QJsonObject &src, AppBskyAgeassuranceDefs::ConfigRegion &dest);
void copyConfig(const QJsonObject &src, AppBskyAgeassuranceDefs::Config &dest);
void copyEvent(const QJsonObject &src, AppBskyAgeassuranceDefs::Event &dest);
}
// app.bsky.bookmark.defs
namespace AppBskyBookmarkDefs {
void copyBookmark(const QJsonObject &src, AppBskyBookmarkDefs::Bookmark &dest);
void copyBookmarkView(const QJsonObject &src, AppBskyBookmarkDefs::BookmarkView &dest);
}
// app.bsky.feed.defs
namespace AppBskyFeedDefs {
void copyBlockedAuthor(const QJsonObject &src, AppBskyFeedDefs::BlockedAuthor &dest);
void copyBlockedPost(const QJsonObject &src, AppBskyFeedDefs::BlockedPost &dest);
void copyNotFoundPost(const QJsonObject &src, AppBskyFeedDefs::NotFoundPost &dest);
void copyGeneratorViewerState(const QJsonObject &src, AppBskyFeedDefs::GeneratorViewerState &dest);
void copyGeneratorView(const QJsonObject &src, AppBskyFeedDefs::GeneratorView &dest);
void copyViewerState(const QJsonObject &src, AppBskyFeedDefs::ViewerState &dest);
void copyThreadgateView(const QJsonObject &src, AppBskyFeedDefs::ThreadgateView &dest);
void copyPostView(const QJsonObject &src, AppBskyFeedDefs::PostView &dest);
void copyThreadContext(const QJsonObject &src, AppBskyFeedDefs::ThreadContext &dest);
void copyReplyRef(const QJsonObject &src, AppBskyFeedDefs::ReplyRef &dest);
void copyReasonRepost(const QJsonObject &src, AppBskyFeedDefs::ReasonRepost &dest);
void copyReasonPin(const QJsonObject &src, AppBskyFeedDefs::ReasonPin &dest);
void copyFeedViewPost(const QJsonObject &src, AppBskyFeedDefs::FeedViewPost &dest);
void copyThreadViewPost(const QJsonObject &src, AppBskyFeedDefs::ThreadViewPost &dest);
void copySkeletonReasonRepost(const QJsonObject &src, AppBskyFeedDefs::SkeletonReasonRepost &dest);
void copySkeletonReasonPin(const QJsonObject &src, AppBskyFeedDefs::SkeletonReasonPin &dest);
void copySkeletonFeedPost(const QJsonObject &src, AppBskyFeedDefs::SkeletonFeedPost &dest);
void copyInteraction(const QJsonObject &src, AppBskyFeedDefs::Interaction &dest);
}
// app.bsky.embed.defs
namespace AppBskyEmbedDefs {
void copyAspectRatio(const QJsonObject &src, AppBskyEmbedDefs::AspectRatio &dest);
}
// app.bsky.embed.images
namespace AppBskyEmbedImages {
void copyViewImage(const QJsonObject &src, AppBskyEmbedImages::ViewImage &dest);
void copyView(const QJsonObject &src, AppBskyEmbedImages::View &dest);
void copyImage(const QJsonObject &src, AppBskyEmbedImages::Image &dest);
void copyMain(const QJsonObject &src, AppBskyEmbedImages::Main &dest);
}
// app.bsky.embed.video
namespace AppBskyEmbedVideo {
void copyView(const QJsonObject &src, AppBskyEmbedVideo::View &dest);
void copyCaption(const QJsonObject &src, AppBskyEmbedVideo::Caption &dest);
void copyMain(const QJsonObject &src, AppBskyEmbedVideo::Main &dest);
}
// app.bsky.embed.gallery
namespace AppBskyEmbedGallery {
void copyViewImage(const QJsonObject &src, AppBskyEmbedGallery::ViewImage &dest);
void copyView(const QJsonObject &src, AppBskyEmbedGallery::View &dest);
void copyImage(const QJsonObject &src, AppBskyEmbedGallery::Image &dest);
void copyMain(const QJsonObject &src, AppBskyEmbedGallery::Main &dest);
}
// app.bsky.embed.recordWithMedia
namespace AppBskyEmbedRecordWithMedia {
void copyView(const QJsonObject &src, AppBskyEmbedRecordWithMedia::View &dest);
void copyMain(const QJsonObject &src, AppBskyEmbedRecordWithMedia::Main &dest);
}
// app.bsky.embed.record
namespace AppBskyEmbedRecord {
void copyViewRecord(const QJsonObject &src, AppBskyEmbedRecord::ViewRecord &dest);
void copyViewNotFound(const QJsonObject &src, AppBskyEmbedRecord::ViewNotFound &dest);
void copyViewBlocked(const QJsonObject &src, AppBskyEmbedRecord::ViewBlocked &dest);
void copyViewDetached(const QJsonObject &src, AppBskyEmbedRecord::ViewDetached &dest);
void copyView(const QJsonObject &src, AppBskyEmbedRecord::View &dest);
void copyMain(const QJsonObject &src, AppBskyEmbedRecord::Main &dest);
}
// app.bsky.richtext.facet
namespace AppBskyRichtextFacet {
void copyByteSlice(const QJsonObject &src, AppBskyRichtextFacet::ByteSlice &dest);
void copyMention(const QJsonObject &src, AppBskyRichtextFacet::Mention &dest);
void copyLink(const QJsonObject &src, AppBskyRichtextFacet::Link &dest);
void copyTag(const QJsonObject &src, AppBskyRichtextFacet::Tag &dest);
void copyMain(const QJsonObject &src, AppBskyRichtextFacet::Main &dest);
}
// app.bsky.labeler.defs
namespace AppBskyLabelerDefs {
void copyLabelerViewerState(const QJsonObject &src, AppBskyLabelerDefs::LabelerViewerState &dest);
void copyLabelerView(const QJsonObject &src, AppBskyLabelerDefs::LabelerView &dest);
void copyLabelerPolicies(const QJsonObject &src, AppBskyLabelerDefs::LabelerPolicies &dest);
void copyLabelerViewDetailed(const QJsonObject &src, AppBskyLabelerDefs::LabelerViewDetailed &dest);
}
// app.bsky.contact.defs
namespace AppBskyContactDefs {
void copyMatchAndContactIndex(const QJsonObject &src,
                              AppBskyContactDefs::MatchAndContactIndex &dest);
void copySyncStatus(const QJsonObject &src, AppBskyContactDefs::SyncStatus &dest);
void copyNotification(const QJsonObject &src, AppBskyContactDefs::Notification &dest);
}
// app.bsky.draft.defs
namespace AppBskyDraftDefs {
void copyDraftEmbedLocalRef(const QJsonObject &src, AppBskyDraftDefs::DraftEmbedLocalRef &dest);
void copyDraftEmbedImage(const QJsonObject &src, AppBskyDraftDefs::DraftEmbedImage &dest);
void copyDraftEmbedGalleryItems(const QJsonArray &src,
                                AppBskyDraftDefs::DraftEmbedGalleryItems &dest);
void copyDraftEmbedGallery(const QJsonObject &src, AppBskyDraftDefs::DraftEmbedGallery &dest);
void copyDraftEmbedCaption(const QJsonObject &src, AppBskyDraftDefs::DraftEmbedCaption &dest);
void copyDraftEmbedVideo(const QJsonObject &src, AppBskyDraftDefs::DraftEmbedVideo &dest);
void copyDraftEmbedExternal(const QJsonObject &src, AppBskyDraftDefs::DraftEmbedExternal &dest);
void copyDraftEmbedRecord(const QJsonObject &src, AppBskyDraftDefs::DraftEmbedRecord &dest);
void copyDraftPost(const QJsonObject &src, AppBskyDraftDefs::DraftPost &dest);
void copyDraft(const QJsonObject &src, AppBskyDraftDefs::Draft &dest);
void copyDraftWithId(const QJsonObject &src, AppBskyDraftDefs::DraftWithId &dest);
void copyDraftView(const QJsonObject &src, AppBskyDraftDefs::DraftView &dest);
}
// app.bsky.feed.describeFeedGenerator
namespace AppBskyFeedDescribeFeedGenerator {
void copyFeed(const QJsonObject &src, AppBskyFeedDescribeFeedGenerator::Feed &dest);
void copyLinks(const QJsonObject &src, AppBskyFeedDescribeFeedGenerator::Links &dest);
}
// app.bsky.feed.generator
namespace AppBskyFeedGenerator {
void copyMain(const QJsonObject &src, AppBskyFeedGenerator::Main &dest);
}
// app.bsky.feed.getLikes
namespace AppBskyFeedGetLikes {
void copyLike(const QJsonObject &src, AppBskyFeedGetLikes::Like &dest);
}
// app.bsky.feed.like
namespace AppBskyFeedLike {
void copyMain(const QJsonObject &src, AppBskyFeedLike::Main &dest);
}
// app.bsky.feed.post
namespace AppBskyFeedPost {
void copyTextSlice(const QJsonObject &src, AppBskyFeedPost::TextSlice &dest);
void copyEntity(const QJsonObject &src, AppBskyFeedPost::Entity &dest);
void copyReplyRef(const QJsonObject &src, AppBskyFeedPost::ReplyRef &dest);
void copyMain(const QJsonObject &src, AppBskyFeedPost::Main &dest);
}
// app.bsky.feed.repost
namespace AppBskyFeedRepost {
void copyMain(const QJsonObject &src, AppBskyFeedRepost::Main &dest);
}
// app.bsky.graph.block
namespace AppBskyGraphBlock {
void copyMain(const QJsonObject &src, AppBskyGraphBlock::Main &dest);
}
// app.bsky.graph.follow
namespace AppBskyGraphFollow {
void copyMain(const QJsonObject &src, AppBskyGraphFollow::Main &dest);
}
// app.bsky.graph.getListsWithMembership
namespace AppBskyGraphGetListsWithMembership {
void copyListWithMembership(const QJsonObject &src,
                            AppBskyGraphGetListsWithMembership::ListWithMembership &dest);
}
// app.bsky.graph.getStarterPacksWithMembership
namespace AppBskyGraphGetStarterPacksWithMembership {
void copyStarterPackWithMembership(
        const QJsonObject &src,
        AppBskyGraphGetStarterPacksWithMembership::StarterPackWithMembership &dest);
}
// app.bsky.graph.list
namespace AppBskyGraphList {
void copyMain(const QJsonObject &src, AppBskyGraphList::Main &dest);
}
// app.bsky.graph.listblock
namespace AppBskyGraphListblock {
void copyMain(const QJsonObject &src, AppBskyGraphListblock::Main &dest);
}
// app.bsky.graph.listitem
namespace AppBskyGraphListitem {
void copyMain(const QJsonObject &src, AppBskyGraphListitem::Main &dest);
}
// app.bsky.graph.starterpack
namespace AppBskyGraphStarterpack {
void copyFeedItem(const QJsonObject &src, AppBskyGraphStarterpack::FeedItem &dest);
void copyMain(const QJsonObject &src, AppBskyGraphStarterpack::Main &dest);
}
// app.bsky.graph.verification
namespace AppBskyGraphVerification {
void copyMain(const QJsonObject &src, AppBskyGraphVerification::Main &dest);
}
// com.atproto.moderation.defs
namespace ComAtprotoModerationDefs {
void copyReasonType(const QJsonValue &src, ComAtprotoModerationDefs::ReasonType &dest);
void copySubjectType(const QJsonValue &src, ComAtprotoModerationDefs::SubjectType &dest);
}
// app.bsky.labeler.service
namespace AppBskyLabelerService {
void copyMain(const QJsonObject &src, AppBskyLabelerService::Main &dest);
}
// app.bsky.notification.declaration
namespace AppBskyNotificationDeclaration {
void copyMain(const QJsonObject &src, AppBskyNotificationDeclaration::Main &dest);
}
// app.bsky.notification.listNotifications
namespace AppBskyNotificationListNotifications {
void copyNotification(const QJsonObject &src,
                      AppBskyNotificationListNotifications::Notification &dest);
}
// app.bsky.unspecced.defs
namespace AppBskyUnspeccedDefs {
void copySkeletonSearchPost(const QJsonObject &src, AppBskyUnspeccedDefs::SkeletonSearchPost &dest);
void copySkeletonSearchActor(const QJsonObject &src,
                             AppBskyUnspeccedDefs::SkeletonSearchActor &dest);
void copySkeletonSearchStarterPack(const QJsonObject &src,
                                   AppBskyUnspeccedDefs::SkeletonSearchStarterPack &dest);
void copyTrendingTopic(const QJsonObject &src, AppBskyUnspeccedDefs::TrendingTopic &dest);
void copySkeletonTrend(const QJsonObject &src, AppBskyUnspeccedDefs::SkeletonTrend &dest);
void copyTrendView(const QJsonObject &src, AppBskyUnspeccedDefs::TrendView &dest);
void copyThreadItemPost(const QJsonObject &src, AppBskyUnspeccedDefs::ThreadItemPost &dest);
void copyThreadItemNoUnauthenticated(const QJsonObject &src,
                                     AppBskyUnspeccedDefs::ThreadItemNoUnauthenticated &dest);
void copyThreadItemNotFound(const QJsonObject &src, AppBskyUnspeccedDefs::ThreadItemNotFound &dest);
void copyThreadItemBlocked(const QJsonObject &src, AppBskyUnspeccedDefs::ThreadItemBlocked &dest);
void copyAgeAssuranceState(const QJsonObject &src, AppBskyUnspeccedDefs::AgeAssuranceState &dest);
void copyAgeAssuranceEvent(const QJsonObject &src, AppBskyUnspeccedDefs::AgeAssuranceEvent &dest);
}
// app.bsky.unspecced.getConfig
namespace AppBskyUnspeccedGetConfig {
void copyLiveNowConfig(const QJsonObject &src, AppBskyUnspeccedGetConfig::LiveNowConfig &dest);
}
// app.bsky.unspecced.getPostThreadOtherV2
namespace AppBskyUnspeccedGetPostThreadOtherV2 {
void copyThreadItem(const QJsonObject &src, AppBskyUnspeccedGetPostThreadOtherV2::ThreadItem &dest);
}
// app.bsky.unspecced.getPostThreadV2
namespace AppBskyUnspeccedGetPostThreadV2 {
void copyThreadItem(const QJsonObject &src, AppBskyUnspeccedGetPostThreadV2::ThreadItem &dest);
}
// app.bsky.unspecced.getTaggedSuggestions
namespace AppBskyUnspeccedGetTaggedSuggestions {
void copySuggestion(const QJsonObject &src, AppBskyUnspeccedGetTaggedSuggestions::Suggestion &dest);
}
// app.bsky.video.defs
namespace AppBskyVideoDefs {
void copyJobStatus(const QJsonObject &src, AppBskyVideoDefs::JobStatus &dest);
}
// chat.bsky.actor.declaration
namespace ChatBskyActorDeclaration {
void copyMain(const QJsonObject &src, ChatBskyActorDeclaration::Main &dest);
}
// chat.bsky.actor.defs
namespace ChatBskyActorDefs {
void copyMemberRole(const QJsonValue &src, ChatBskyActorDefs::MemberRole &dest);
void copyDirectConvoMember(const QJsonObject &src, ChatBskyActorDefs::DirectConvoMember &dest);
void copyGroupConvoMember(const QJsonObject &src, ChatBskyActorDefs::GroupConvoMember &dest);
void copyPastGroupConvoMember(const QJsonObject &src,
                              ChatBskyActorDefs::PastGroupConvoMember &dest);
void copyProfileViewBasic(const QJsonObject &src, ChatBskyActorDefs::ProfileViewBasic &dest);
}
// chat.bsky.convo.defs
namespace ChatBskyConvoDefs {
void copyConvoKind(const QJsonValue &src, ChatBskyConvoDefs::ConvoKind &dest);
void copyConvoLockStatus(const QJsonValue &src, ChatBskyConvoDefs::ConvoLockStatus &dest);
void copyConvoStatus(const QJsonValue &src, ChatBskyConvoDefs::ConvoStatus &dest);
void copyConvoRef(const QJsonObject &src, ChatBskyConvoDefs::ConvoRef &dest);
void copyMessageRef(const QJsonObject &src, ChatBskyConvoDefs::MessageRef &dest);
void copyMessageInput(const QJsonObject &src, ChatBskyConvoDefs::MessageInput &dest);
void copyMessageViewSender(const QJsonObject &src, ChatBskyConvoDefs::MessageViewSender &dest);
void copyDeletedMessageView(const QJsonObject &src, ChatBskyConvoDefs::DeletedMessageView &dest);
void copySystemMessageReferredUser(const QJsonObject &src,
                                   ChatBskyConvoDefs::SystemMessageReferredUser &dest);
void copySystemMessageDataAddMember(const QJsonObject &src,
                                    ChatBskyConvoDefs::SystemMessageDataAddMember &dest);
void copySystemMessageDataRemoveMember(const QJsonObject &src,
                                       ChatBskyConvoDefs::SystemMessageDataRemoveMember &dest);
void copySystemMessageDataMemberJoin(const QJsonObject &src,
                                     ChatBskyConvoDefs::SystemMessageDataMemberJoin &dest);
void copySystemMessageDataMemberLeave(const QJsonObject &src,
                                      ChatBskyConvoDefs::SystemMessageDataMemberLeave &dest);
void copySystemMessageDataLockConvo(const QJsonObject &src,
                                    ChatBskyConvoDefs::SystemMessageDataLockConvo &dest);
void copySystemMessageDataUnlockConvo(const QJsonObject &src,
                                      ChatBskyConvoDefs::SystemMessageDataUnlockConvo &dest);
void copySystemMessageDataLockConvoPermanently(
        const QJsonObject &src, ChatBskyConvoDefs::SystemMessageDataLockConvoPermanently &dest);
void copySystemMessageDataEditGroup(const QJsonObject &src,
                                    ChatBskyConvoDefs::SystemMessageDataEditGroup &dest);
void copySystemMessageDataCreateJoinLink(const QJsonObject &src,
                                         ChatBskyConvoDefs::SystemMessageDataCreateJoinLink &dest);
void copySystemMessageDataEditJoinLink(const QJsonObject &src,
                                       ChatBskyConvoDefs::SystemMessageDataEditJoinLink &dest);
void copySystemMessageDataEnableJoinLink(const QJsonObject &src,
                                         ChatBskyConvoDefs::SystemMessageDataEnableJoinLink &dest);
void copySystemMessageDataDisableJoinLink(
        const QJsonObject &src, ChatBskyConvoDefs::SystemMessageDataDisableJoinLink &dest);
void copySystemMessageView(const QJsonObject &src, ChatBskyConvoDefs::SystemMessageView &dest);
void copyReactionViewSender(const QJsonObject &src, ChatBskyConvoDefs::ReactionViewSender &dest);
void copyReactionView(const QJsonObject &src, ChatBskyConvoDefs::ReactionView &dest);
void copyMessageAndReactionView(const QJsonObject &src,
                                ChatBskyConvoDefs::MessageAndReactionView &dest);
void copyDirectConvo(const QJsonObject &src, ChatBskyConvoDefs::DirectConvo &dest);
void copyGroupConvo(const QJsonObject &src, ChatBskyConvoDefs::GroupConvo &dest);
void copyConvoView(const QJsonObject &src, ChatBskyConvoDefs::ConvoView &dest);
void copyMessageView(const QJsonObject &src, ChatBskyConvoDefs::MessageView &dest);
void copyLogBeginConvo(const QJsonObject &src, ChatBskyConvoDefs::LogBeginConvo &dest);
void copyLogAcceptConvo(const QJsonObject &src, ChatBskyConvoDefs::LogAcceptConvo &dest);
void copyLogLeaveConvo(const QJsonObject &src, ChatBskyConvoDefs::LogLeaveConvo &dest);
void copyLogMuteConvo(const QJsonObject &src, ChatBskyConvoDefs::LogMuteConvo &dest);
void copyLogUnmuteConvo(const QJsonObject &src, ChatBskyConvoDefs::LogUnmuteConvo &dest);
void copyLogCreateMessage(const QJsonObject &src, ChatBskyConvoDefs::LogCreateMessage &dest);
void copyLogDeleteMessage(const QJsonObject &src, ChatBskyConvoDefs::LogDeleteMessage &dest);
void copyLogReadMessage(const QJsonObject &src, ChatBskyConvoDefs::LogReadMessage &dest);
void copyLogAddReaction(const QJsonObject &src, ChatBskyConvoDefs::LogAddReaction &dest);
void copyLogRemoveReaction(const QJsonObject &src, ChatBskyConvoDefs::LogRemoveReaction &dest);
void copyLogReadConvo(const QJsonObject &src, ChatBskyConvoDefs::LogReadConvo &dest);
void copyLogAddMember(const QJsonObject &src, ChatBskyConvoDefs::LogAddMember &dest);
void copyLogRemoveMember(const QJsonObject &src, ChatBskyConvoDefs::LogRemoveMember &dest);
void copyLogMemberJoin(const QJsonObject &src, ChatBskyConvoDefs::LogMemberJoin &dest);
void copyLogMemberLeave(const QJsonObject &src, ChatBskyConvoDefs::LogMemberLeave &dest);
void copyLogLockConvo(const QJsonObject &src, ChatBskyConvoDefs::LogLockConvo &dest);
void copyLogUnlockConvo(const QJsonObject &src, ChatBskyConvoDefs::LogUnlockConvo &dest);
void copyLogLockConvoPermanently(const QJsonObject &src,
                                 ChatBskyConvoDefs::LogLockConvoPermanently &dest);
void copyLogEditGroup(const QJsonObject &src, ChatBskyConvoDefs::LogEditGroup &dest);
void copyLogCreateJoinLink(const QJsonObject &src, ChatBskyConvoDefs::LogCreateJoinLink &dest);
void copyLogEditJoinLink(const QJsonObject &src, ChatBskyConvoDefs::LogEditJoinLink &dest);
void copyLogEnableJoinLink(const QJsonObject &src, ChatBskyConvoDefs::LogEnableJoinLink &dest);
void copyLogDisableJoinLink(const QJsonObject &src, ChatBskyConvoDefs::LogDisableJoinLink &dest);
void copyLogIncomingJoinRequest(const QJsonObject &src,
                                ChatBskyConvoDefs::LogIncomingJoinRequest &dest);
void copyLogApproveJoinRequest(const QJsonObject &src,
                               ChatBskyConvoDefs::LogApproveJoinRequest &dest);
void copyLogRejectJoinRequest(const QJsonObject &src,
                              ChatBskyConvoDefs::LogRejectJoinRequest &dest);
void copyLogOutgoingJoinRequest(const QJsonObject &src,
                                ChatBskyConvoDefs::LogOutgoingJoinRequest &dest);
void copyLogWithdrawIncomingJoinRequest(const QJsonObject &src,
                                        ChatBskyConvoDefs::LogWithdrawIncomingJoinRequest &dest);
void copyLogWithdrawOutgoingJoinRequest(const QJsonObject &src,
                                        ChatBskyConvoDefs::LogWithdrawOutgoingJoinRequest &dest);
void copyLogReadJoinRequests(const QJsonObject &src, ChatBskyConvoDefs::LogReadJoinRequests &dest);
}
// chat.bsky.embed.joinLink
namespace ChatBskyEmbedJoinLink {
void copyMain(const QJsonObject &src, ChatBskyEmbedJoinLink::Main &dest);
void copyView(const QJsonObject &src, ChatBskyEmbedJoinLink::View &dest);
}
// chat.bsky.group.defs
namespace ChatBskyGroupDefs {
void copyJoinRule(const QJsonValue &src, ChatBskyGroupDefs::JoinRule &dest);
void copyLinkEnabledStatus(const QJsonValue &src, ChatBskyGroupDefs::LinkEnabledStatus &dest);
void copyJoinLinkView(const QJsonObject &src, ChatBskyGroupDefs::JoinLinkView &dest);
void copyJoinLinkViewerState(const QJsonObject &src, ChatBskyGroupDefs::JoinLinkViewerState &dest);
void copyJoinLinkPreviewView(const QJsonObject &src, ChatBskyGroupDefs::JoinLinkPreviewView &dest);
void copyDisabledJoinLinkPreviewView(const QJsonObject &src,
                                     ChatBskyGroupDefs::DisabledJoinLinkPreviewView &dest);
void copyInvalidJoinLinkPreviewView(const QJsonObject &src,
                                    ChatBskyGroupDefs::InvalidJoinLinkPreviewView &dest);
void copyJoinRequestView(const QJsonObject &src, ChatBskyGroupDefs::JoinRequestView &dest);
void copyJoinRequestConvoView(const QJsonObject &src,
                              ChatBskyGroupDefs::JoinRequestConvoView &dest);
}
// chat.bsky.convo.sendMessageBatch
namespace ChatBskyConvoSendMessageBatch {
void copyBatchItem(const QJsonObject &src, ChatBskyConvoSendMessageBatch::BatchItem &dest);
}
// chat.bsky.moderation.defs
namespace ChatBskyModerationDefs {
void copyDirectConvo(const QJsonObject &src, ChatBskyModerationDefs::DirectConvo &dest);
void copyGroupConvo(const QJsonObject &src, ChatBskyModerationDefs::GroupConvo &dest);
void copyConvoView(const QJsonObject &src, ChatBskyModerationDefs::ConvoView &dest);
}
// chat.bsky.moderation.getActorMetadata
namespace ChatBskyModerationGetActorMetadata {
void copyMetadata(const QJsonObject &src, ChatBskyModerationGetActorMetadata::Metadata &dest);
}
// chat.bsky.moderation.subscribeModEvents
namespace ChatBskyModerationSubscribeModEvents {
void copyEventConvoFirstMessage(const QJsonObject &src,
                                ChatBskyModerationSubscribeModEvents::EventConvoFirstMessage &dest);
void copyEventGroupChatCreated(const QJsonObject &src,
                               ChatBskyModerationSubscribeModEvents::EventGroupChatCreated &dest);
void copyEventGroupChatMemberAdded(
        const QJsonObject &src,
        ChatBskyModerationSubscribeModEvents::EventGroupChatMemberAdded &dest);
void copyEventGroupChatMemberJoined(
        const QJsonObject &src,
        ChatBskyModerationSubscribeModEvents::EventGroupChatMemberJoined &dest);
void copyEventGroupChatJoinRequest(
        const QJsonObject &src,
        ChatBskyModerationSubscribeModEvents::EventGroupChatJoinRequest &dest);
void copyEventGroupChatJoinRequestApproved(
        const QJsonObject &src,
        ChatBskyModerationSubscribeModEvents::EventGroupChatJoinRequestApproved &dest);
void copyEventGroupChatJoinRequestRejected(
        const QJsonObject &src,
        ChatBskyModerationSubscribeModEvents::EventGroupChatJoinRequestRejected &dest);
void copyEventChatAccepted(const QJsonObject &src,
                           ChatBskyModerationSubscribeModEvents::EventChatAccepted &dest);
void copyEventGroupChatMemberLeft(
        const QJsonObject &src,
        ChatBskyModerationSubscribeModEvents::EventGroupChatMemberLeft &dest);
void copyEventGroupChatUpdated(const QJsonObject &src,
                               ChatBskyModerationSubscribeModEvents::EventGroupChatUpdated &dest);
void copyEventRateLimitExceeded(const QJsonObject &src,
                                ChatBskyModerationSubscribeModEvents::EventRateLimitExceeded &dest);
}
// com.atproto.admin.defs
namespace ComAtprotoAdminDefs {
void copyStatusAttr(const QJsonObject &src, ComAtprotoAdminDefs::StatusAttr &dest);
void copyThreatSignature(const QJsonObject &src, ComAtprotoAdminDefs::ThreatSignature &dest);
void copyAccountView(const QJsonObject &src, ComAtprotoAdminDefs::AccountView &dest);
void copyRepoRef(const QJsonObject &src, ComAtprotoAdminDefs::RepoRef &dest);
void copyRepoBlobRef(const QJsonObject &src, ComAtprotoAdminDefs::RepoBlobRef &dest);
}
// com.atproto.server.defs
namespace ComAtprotoServerDefs {
void copyInviteCodeUse(const QJsonObject &src, ComAtprotoServerDefs::InviteCodeUse &dest);
void copyInviteCode(const QJsonObject &src, ComAtprotoServerDefs::InviteCode &dest);
}
// com.atproto.identity.defs
namespace ComAtprotoIdentityDefs {
void copyIdentityInfo(const QJsonObject &src, ComAtprotoIdentityDefs::IdentityInfo &dest);
}
// com.atproto.label.subscribeLabels
namespace ComAtprotoLabelSubscribeLabels {
void copyLabels(const QJsonObject &src, ComAtprotoLabelSubscribeLabels::Labels &dest);
void copyInfo(const QJsonObject &src, ComAtprotoLabelSubscribeLabels::Info &dest);
}
// com.atproto.lexicon.schema
namespace ComAtprotoLexiconSchema {
void copyMain(const QJsonObject &src, ComAtprotoLexiconSchema::Main &dest);
}
// com.atproto.moderation.createReport
namespace ComAtprotoModerationCreateReport {
void copyModTool(const QJsonObject &src, ComAtprotoModerationCreateReport::ModTool &dest);
}
// com.atproto.repo.applyWrites
namespace ComAtprotoRepoApplyWrites {
void copyCreate(const QJsonObject &src, ComAtprotoRepoApplyWrites::Create &dest);
void copyUpdate(const QJsonObject &src, ComAtprotoRepoApplyWrites::Update &dest);
void copyDelete(const QJsonObject &src, ComAtprotoRepoApplyWrites::Delete &dest);
void copyCreateResult(const QJsonObject &src, ComAtprotoRepoApplyWrites::CreateResult &dest);
void copyUpdateResult(const QJsonObject &src, ComAtprotoRepoApplyWrites::UpdateResult &dest);
void copyDeleteResult(const QJsonObject &src, ComAtprotoRepoApplyWrites::DeleteResult &dest);
}
// com.atproto.repo.defs
namespace ComAtprotoRepoDefs {
void copyCommitMeta(const QJsonObject &src, ComAtprotoRepoDefs::CommitMeta &dest);
}
// com.atproto.repo.listMissingBlobs
namespace ComAtprotoRepoListMissingBlobs {
void copyRecordBlob(const QJsonObject &src, ComAtprotoRepoListMissingBlobs::RecordBlob &dest);
}
// com.atproto.repo.listRecords
namespace ComAtprotoRepoListRecords {
void copyRecord(const QJsonObject &src, ComAtprotoRepoListRecords::Record &dest);
}
// com.atproto.server.createAppPassword
namespace ComAtprotoServerCreateAppPassword {
void copyAppPassword(const QJsonObject &src, ComAtprotoServerCreateAppPassword::AppPassword &dest);
}
// com.atproto.server.createInviteCodes
namespace ComAtprotoServerCreateInviteCodes {
void copyAccountCodes(const QJsonObject &src,
                      ComAtprotoServerCreateInviteCodes::AccountCodes &dest);
}
// com.atproto.server.describeServer
namespace ComAtprotoServerDescribeServer {
void copyLinks(const QJsonObject &src, ComAtprotoServerDescribeServer::Links &dest);
void copyContact(const QJsonObject &src, ComAtprotoServerDescribeServer::Contact &dest);
}
// com.atproto.server.listAppPasswords
namespace ComAtprotoServerListAppPasswords {
void copyAppPassword(const QJsonObject &src, ComAtprotoServerListAppPasswords::AppPassword &dest);
}
// com.atproto.sync.defs
namespace ComAtprotoSyncDefs {
void copyHostStatus(const QJsonValue &src, ComAtprotoSyncDefs::HostStatus &dest);
}
// com.atproto.sync.listHosts
namespace ComAtprotoSyncListHosts {
void copyHost(const QJsonObject &src, ComAtprotoSyncListHosts::Host &dest);
}
// com.atproto.sync.listRepos
namespace ComAtprotoSyncListRepos {
void copyRepo(const QJsonObject &src, ComAtprotoSyncListRepos::Repo &dest);
}
// com.atproto.sync.listReposByCollection
namespace ComAtprotoSyncListReposByCollection {
void copyRepo(const QJsonObject &src, ComAtprotoSyncListReposByCollection::Repo &dest);
}
// com.atproto.sync.subscribeRepos
namespace ComAtprotoSyncSubscribeRepos {
void copyRepoOp(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::RepoOp &dest);
void copyCommit(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::Commit &dest);
void copySync(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::Sync &dest);
void copyIdentity(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::Identity &dest);
void copyAccount(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::Account &dest);
void copyInfo(const QJsonObject &src, ComAtprotoSyncSubscribeRepos::Info &dest);
}
// com.atproto.temp.checkHandleAvailability
namespace ComAtprotoTempCheckHandleAvailability {
void copyResultAvailable(const QJsonObject &src,
                         ComAtprotoTempCheckHandleAvailability::ResultAvailable &dest);
void copySuggestion(const QJsonObject &src,
                    ComAtprotoTempCheckHandleAvailability::Suggestion &dest);
void copyResultUnavailable(const QJsonObject &src,
                           ComAtprotoTempCheckHandleAvailability::ResultUnavailable &dest);
}
// com.germnetwork.declaration
namespace ComGermnetworkDeclaration {
void copyMessageMe(const QJsonObject &src, ComGermnetworkDeclaration::MessageMe &dest);
void copyMain(const QJsonObject &src, ComGermnetworkDeclaration::Main &dest);
}
// site.standard.document
namespace SiteStandardDocument {
void copyContributor(const QJsonObject &src, SiteStandardDocument::Contributor &dest);
void copyMain(const QJsonObject &src, SiteStandardDocument::Main &dest);
}
// site.standard.theme.color
namespace SiteStandardThemeColor {
void copyRgb(const QJsonObject &src, SiteStandardThemeColor::Rgb &dest);
void copyRgba(const QJsonObject &src, SiteStandardThemeColor::Rgba &dest);
}
// site.standard.theme.basic
namespace SiteStandardThemeBasic {
void copyMain(const QJsonObject &src, SiteStandardThemeBasic::Main &dest);
}
// site.standard.publication
namespace SiteStandardPublication {
void copyPreferences(const QJsonObject &src, SiteStandardPublication::Preferences &dest);
void copyMain(const QJsonObject &src, SiteStandardPublication::Main &dest);
}
// site.standard.graph.recommend
namespace SiteStandardGraphRecommend {
void copyMain(const QJsonObject &src, SiteStandardGraphRecommend::Main &dest);
}
// site.standard.graph.subscription
namespace SiteStandardGraphSubscription {
void copyMain(const QJsonObject &src, SiteStandardGraphSubscription::Main &dest);
}
// tools.ozone.communication.defs
namespace ToolsOzoneCommunicationDefs {
void copyTemplateView(const QJsonObject &src, ToolsOzoneCommunicationDefs::TemplateView &dest);
}
// tools.ozone.hosting.getAccountHistory
namespace ToolsOzoneHostingGetAccountHistory {
void copyAccountCreated(const QJsonObject &src,
                        ToolsOzoneHostingGetAccountHistory::AccountCreated &dest);
void copyEmailUpdated(const QJsonObject &src,
                      ToolsOzoneHostingGetAccountHistory::EmailUpdated &dest);
void copyEmailConfirmed(const QJsonObject &src,
                        ToolsOzoneHostingGetAccountHistory::EmailConfirmed &dest);
void copyPasswordUpdated(const QJsonObject &src,
                         ToolsOzoneHostingGetAccountHistory::PasswordUpdated &dest);
void copyHandleUpdated(const QJsonObject &src,
                       ToolsOzoneHostingGetAccountHistory::HandleUpdated &dest);
void copyEvent(const QJsonObject &src, ToolsOzoneHostingGetAccountHistory::Event &dest);
}
// tools.ozone.moderation.cancelScheduledActions
namespace ToolsOzoneModerationCancelScheduledActions {
void copyFailedCancellation(const QJsonObject &src,
                            ToolsOzoneModerationCancelScheduledActions::FailedCancellation &dest);
void copyCancellationResults(const QJsonObject &src,
                             ToolsOzoneModerationCancelScheduledActions::CancellationResults &dest);
}
// tools.ozone.moderation.defs
namespace ToolsOzoneModerationDefs {
void copyModEventTakedown(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventTakedown &dest);
void copyModEventReverseTakedown(const QJsonObject &src,
                                 ToolsOzoneModerationDefs::ModEventReverseTakedown &dest);
void copyModEventComment(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventComment &dest);
void copyModEventReport(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventReport &dest);
void copyModEventLabel(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventLabel &dest);
void copyModEventAcknowledge(const QJsonObject &src,
                             ToolsOzoneModerationDefs::ModEventAcknowledge &dest);
void copyModEventEscalate(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventEscalate &dest);
void copyModEventMute(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventMute &dest);
void copyModEventUnmute(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventUnmute &dest);
void copyModEventMuteReporter(const QJsonObject &src,
                              ToolsOzoneModerationDefs::ModEventMuteReporter &dest);
void copyModEventUnmuteReporter(const QJsonObject &src,
                                ToolsOzoneModerationDefs::ModEventUnmuteReporter &dest);
void copyModEventEmail(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventEmail &dest);
void copyModEventResolveAppeal(const QJsonObject &src,
                               ToolsOzoneModerationDefs::ModEventResolveAppeal &dest);
void copyModEventDivert(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventDivert &dest);
void copyModEventTag(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventTag &dest);
void copyAccountEvent(const QJsonObject &src, ToolsOzoneModerationDefs::AccountEvent &dest);
void copyIdentityEvent(const QJsonObject &src, ToolsOzoneModerationDefs::IdentityEvent &dest);
void copyRecordEvent(const QJsonObject &src, ToolsOzoneModerationDefs::RecordEvent &dest);
void copyModEventPriorityScore(const QJsonObject &src,
                               ToolsOzoneModerationDefs::ModEventPriorityScore &dest);
void copyAgeAssuranceEvent(const QJsonObject &src,
                           ToolsOzoneModerationDefs::AgeAssuranceEvent &dest);
void copyAgeAssuranceOverrideEvent(const QJsonObject &src,
                                   ToolsOzoneModerationDefs::AgeAssuranceOverrideEvent &dest);
void copyAgeAssurancePurgeEvent(const QJsonObject &src,
                                ToolsOzoneModerationDefs::AgeAssurancePurgeEvent &dest);
void copyRevokeAccountCredentialsEvent(
        const QJsonObject &src, ToolsOzoneModerationDefs::RevokeAccountCredentialsEvent &dest);
void copyScheduleTakedownEvent(const QJsonObject &src,
                               ToolsOzoneModerationDefs::ScheduleTakedownEvent &dest);
void copyCancelScheduledTakedownEvent(const QJsonObject &src,
                                      ToolsOzoneModerationDefs::CancelScheduledTakedownEvent &dest);
void copyModTool(const QJsonObject &src, ToolsOzoneModerationDefs::ModTool &dest);
void copyModEventView(const QJsonObject &src, ToolsOzoneModerationDefs::ModEventView &dest);
void copyAccountHosting(const QJsonObject &src, ToolsOzoneModerationDefs::AccountHosting &dest);
void copyRecordHosting(const QJsonObject &src, ToolsOzoneModerationDefs::RecordHosting &dest);
void copySubjectReviewState(const QJsonValue &src,
                            ToolsOzoneModerationDefs::SubjectReviewState &dest);
void copyAccountStats(const QJsonObject &src, ToolsOzoneModerationDefs::AccountStats &dest);
void copyRecordsStats(const QJsonObject &src, ToolsOzoneModerationDefs::RecordsStats &dest);
void copyAccountStrike(const QJsonObject &src, ToolsOzoneModerationDefs::AccountStrike &dest);
void copySubjectStatusView(const QJsonObject &src,
                           ToolsOzoneModerationDefs::SubjectStatusView &dest);
void copyModeration(const QJsonObject &src, ToolsOzoneModerationDefs::Moderation &dest);
void copyRepoView(const QJsonObject &src, ToolsOzoneModerationDefs::RepoView &dest);
void copyRepoViewNotFound(const QJsonObject &src, ToolsOzoneModerationDefs::RepoViewNotFound &dest);
void copyRecordView(const QJsonObject &src, ToolsOzoneModerationDefs::RecordView &dest);
void copyRecordViewNotFound(const QJsonObject &src,
                            ToolsOzoneModerationDefs::RecordViewNotFound &dest);
void copyConvoView(const QJsonObject &src, ToolsOzoneModerationDefs::ConvoView &dest);
void copyImageDetails(const QJsonObject &src, ToolsOzoneModerationDefs::ImageDetails &dest);
void copyVideoDetails(const QJsonObject &src, ToolsOzoneModerationDefs::VideoDetails &dest);
void copyBlobView(const QJsonObject &src, ToolsOzoneModerationDefs::BlobView &dest);
void copyModEventViewDetail(const QJsonObject &src,
                            ToolsOzoneModerationDefs::ModEventViewDetail &dest);
void copyModerationDetail(const QJsonObject &src, ToolsOzoneModerationDefs::ModerationDetail &dest);
void copyRepoViewDetail(const QJsonObject &src, ToolsOzoneModerationDefs::RepoViewDetail &dest);
void copyRecordViewDetail(const QJsonObject &src, ToolsOzoneModerationDefs::RecordViewDetail &dest);
void copySubjectView(const QJsonObject &src, ToolsOzoneModerationDefs::SubjectView &dest);
void copyReporterStats(const QJsonObject &src, ToolsOzoneModerationDefs::ReporterStats &dest);
void copyScheduledActionView(const QJsonObject &src,
                             ToolsOzoneModerationDefs::ScheduledActionView &dest);
}
// tools.ozone.moderation.emitEvent
namespace ToolsOzoneModerationEmitEvent {
void copyReportAction(const QJsonObject &src, ToolsOzoneModerationEmitEvent::ReportAction &dest);
}
// tools.ozone.moderation.getAccountTimeline
namespace ToolsOzoneModerationGetAccountTimeline {
void copyTimelineItemSummary(const QJsonObject &src,
                             ToolsOzoneModerationGetAccountTimeline::TimelineItemSummary &dest);
void copyTimelineItem(const QJsonObject &src,
                      ToolsOzoneModerationGetAccountTimeline::TimelineItem &dest);
}
// tools.ozone.moderation.scheduleAction
namespace ToolsOzoneModerationScheduleAction {
void copyTakedown(const QJsonObject &src, ToolsOzoneModerationScheduleAction::Takedown &dest);
void copySchedulingConfig(const QJsonObject &src,
                          ToolsOzoneModerationScheduleAction::SchedulingConfig &dest);
void copyFailedScheduling(const QJsonObject &src,
                          ToolsOzoneModerationScheduleAction::FailedScheduling &dest);
void copyScheduledActionResults(const QJsonObject &src,
                                ToolsOzoneModerationScheduleAction::ScheduledActionResults &dest);
}
// tools.ozone.queue.defs
namespace ToolsOzoneQueueDefs {
void copyQueueStats(const QJsonObject &src, ToolsOzoneQueueDefs::QueueStats &dest);
void copyQueueView(const QJsonObject &src, ToolsOzoneQueueDefs::QueueView &dest);
void copyAssignmentView(const QJsonObject &src, ToolsOzoneQueueDefs::AssignmentView &dest);
}
// tools.ozone.team.defs
namespace ToolsOzoneTeamDefs {
void copyMember(const QJsonObject &src, ToolsOzoneTeamDefs::Member &dest);
}
// tools.ozone.report.defs
namespace ToolsOzoneReportDefs {
void copyReasonType(const QJsonValue &src, ToolsOzoneReportDefs::ReasonType &dest);
void copyReportAssignment(const QJsonObject &src, ToolsOzoneReportDefs::ReportAssignment &dest);
void copyReportView(const QJsonObject &src, ToolsOzoneReportDefs::ReportView &dest);
void copyQueueActivity(const QJsonObject &src, ToolsOzoneReportDefs::QueueActivity &dest);
void copyAssignmentActivity(const QJsonObject &src, ToolsOzoneReportDefs::AssignmentActivity &dest);
void copyEscalationActivity(const QJsonObject &src, ToolsOzoneReportDefs::EscalationActivity &dest);
void copyCloseActivity(const QJsonObject &src, ToolsOzoneReportDefs::CloseActivity &dest);
void copyReopenActivity(const QJsonObject &src, ToolsOzoneReportDefs::ReopenActivity &dest);
void copyNoteActivity(const QJsonObject &src, ToolsOzoneReportDefs::NoteActivity &dest);
void copyReportActivityView(const QJsonObject &src, ToolsOzoneReportDefs::ReportActivityView &dest);
void copyLiveStats(const QJsonObject &src, ToolsOzoneReportDefs::LiveStats &dest);
void copyHistoricalStats(const QJsonObject &src, ToolsOzoneReportDefs::HistoricalStats &dest);
void copyAssignmentView(const QJsonObject &src, ToolsOzoneReportDefs::AssignmentView &dest);
}
// tools.ozone.safelink.defs
namespace ToolsOzoneSafelinkDefs {
void copyEventType(const QJsonValue &src, ToolsOzoneSafelinkDefs::EventType &dest);
void copyPatternType(const QJsonValue &src, ToolsOzoneSafelinkDefs::PatternType &dest);
void copyActionType(const QJsonValue &src, ToolsOzoneSafelinkDefs::ActionType &dest);
void copyReasonType(const QJsonValue &src, ToolsOzoneSafelinkDefs::ReasonType &dest);
void copyEvent(const QJsonObject &src, ToolsOzoneSafelinkDefs::Event &dest);
void copyUrlRule(const QJsonObject &src, ToolsOzoneSafelinkDefs::UrlRule &dest);
}
// tools.ozone.server.getConfig
namespace ToolsOzoneServerGetConfig {
void copyServiceConfig(const QJsonObject &src, ToolsOzoneServerGetConfig::ServiceConfig &dest);
void copyViewerConfig(const QJsonObject &src, ToolsOzoneServerGetConfig::ViewerConfig &dest);
}
// tools.ozone.set.defs
namespace ToolsOzoneSetDefs {
void copySet(const QJsonObject &src, ToolsOzoneSetDefs::Set &dest);
void copySetView(const QJsonObject &src, ToolsOzoneSetDefs::SetView &dest);
}
// tools.ozone.setting.defs
namespace ToolsOzoneSettingDefs {
void copyOption(const QJsonObject &src, ToolsOzoneSettingDefs::Option &dest);
}
// tools.ozone.signature.defs
namespace ToolsOzoneSignatureDefs {
void copySigDetail(const QJsonObject &src, ToolsOzoneSignatureDefs::SigDetail &dest);
}
// tools.ozone.signature.findRelatedAccounts
namespace ToolsOzoneSignatureFindRelatedAccounts {
void copyRelatedAccount(const QJsonObject &src,
                        ToolsOzoneSignatureFindRelatedAccounts::RelatedAccount &dest);
}
// tools.ozone.verification.defs
namespace ToolsOzoneVerificationDefs {
void copyVerificationView(const QJsonObject &src,
                          ToolsOzoneVerificationDefs::VerificationView &dest);
}
// tools.ozone.verification.grantVerifications
namespace ToolsOzoneVerificationGrantVerifications {
void copyVerificationInput(const QJsonObject &src,
                           ToolsOzoneVerificationGrantVerifications::VerificationInput &dest);
void copyGrantError(const QJsonObject &src,
                    ToolsOzoneVerificationGrantVerifications::GrantError &dest);
}
// tools.ozone.verification.revokeVerifications
namespace ToolsOzoneVerificationRevokeVerifications {
void copyRevokeError(const QJsonObject &src,
                     ToolsOzoneVerificationRevokeVerifications::RevokeError &dest);
}
// blue.linkat.defs
namespace BlueLinkatDefs {
void copyCard(const QJsonObject &src, BlueLinkatDefs::Card &dest);
}
// blue.linkat.board
namespace BlueLinkatBoard {
void copyMain(const QJsonObject &src, BlueLinkatBoard::Main &dest);
}
// com.whtwnd.blog.defs
namespace ComWhtwndBlogDefs {
void copyBlogEntry(const QJsonObject &src, ComWhtwndBlogDefs::BlogEntry &dest);
void copyComment(const QJsonObject &src, ComWhtwndBlogDefs::Comment &dest);
void copyOgp(const QJsonObject &src, ComWhtwndBlogDefs::Ogp &dest);
void copyBlobMetadata(const QJsonObject &src, ComWhtwndBlogDefs::BlobMetadata &dest);
}
// com.whtwnd.blog.entry
namespace ComWhtwndBlogEntry {
void copyMain(const QJsonObject &src, ComWhtwndBlogEntry::Main &dest);
}
// directory.plc.defs
namespace DirectoryPlcDefs {
void copyDidDocVerificationMethod(const QJsonObject &src,
                                  DirectoryPlcDefs::DidDocVerificationMethod &dest);
void copyDidDocService(const QJsonObject &src, DirectoryPlcDefs::DidDocService &dest);
void copyDidDoc(const QJsonObject &src, DirectoryPlcDefs::DidDoc &dest);
void copyPlcLogAtprotoPds(const QJsonObject &src, DirectoryPlcDefs::PlcLogAtprotoPds &dest);
void copyPlcLogService(const QJsonObject &src, DirectoryPlcDefs::PlcLogService &dest);
void copyPlcLogVerificationMethods(const QJsonObject &src,
                                   DirectoryPlcDefs::PlcLogVerificationMethods &dest);
void copyPlc_operation(const QJsonObject &src, DirectoryPlcDefs::Plc_operation &dest);
void copyPlc_tombstone(const QJsonObject &src, DirectoryPlcDefs::Plc_tombstone &dest);
void copyCreate(const QJsonObject &src, DirectoryPlcDefs::Create &dest);
void copyPlcAuditLogDetail(const QJsonObject &src, DirectoryPlcDefs::PlcAuditLogDetail &dest);
void copyPlcAuditLog(const QJsonArray &src, DirectoryPlcDefs::PlcAuditLog &dest);
}
// oauth.defs
namespace OauthDefs {
void copyPushedAuthorizationResponse(const QJsonObject &src,
                                     OauthDefs::PushedAuthorizationResponse &dest);
void copyTokenResponse(const QJsonObject &src, OauthDefs::TokenResponse &dest);
}
// tech.tokimeki.poll.defs
namespace TechTokimekiPollDefs {
void copyPollRecordView(const QJsonObject &src, TechTokimekiPollDefs::PollRecordView &dest);
void copyPollOptionTally(const QJsonObject &src, TechTokimekiPollDefs::PollOptionTally &dest);
void copyPollViewDetailed(const QJsonObject &src, TechTokimekiPollDefs::PollViewDetailed &dest);
}
// uk.skyblur.post
namespace UkSkyblurPost {
void copyMain(const QJsonObject &src, UkSkyblurPost::Main &dest);
}
// wellKnown.defs
namespace WellKnownDefs {
void copyResourceMetadata(const QJsonObject &src, WellKnownDefs::ResourceMetadata &dest);
void copyServerMetadata(const QJsonObject &src, WellKnownDefs::ServerMetadata &dest);
}

}

#endif // LEXICONS_FUNC_H
