baseURL = 'https://hagoromo.relog.tech/'
theme = 'hugo-book'

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = 'en-US'
    weight = 10
    title = '羽衣 -Hagoromo-'
    description = 'This is a multi-column Bluesky client.'
    images = ['images/cover.png']
  [languages.ja]
    languageName = "日本語"
    languageCode = 'ja-JP'
    weight = 20
    title = '羽衣 -Hagoromo-'
    description = 'This is a multi-column Bluesky client.'
    images = ['images/cover.png']
